Actions =("Full",((
    ("OpenDialog","Show Open dialog","Show Open dialog.",u'{O}'),
    ("ReopenFile","Reopen file","Reopen file.",u'{Shift+R}'),
    ("OpenInExternal","Open in external","Open in external viewer/editor.",u'{Shift+E}'),
    ("Thumbnails","Thumbnails","Thumbnails.",u'{T}'),
    ("SlideshowDialog","Show Slideshow dialog","Show Slideshow dialog.",u'{W}'),
    ("BatchConversionRename","Batch Conversion/Rename","Batch Conversion/Rename.",u'{B}'),
    ("RenameFile","Rename file","Rename file.",u'{F2}'),
    ("MoveFile","Move file","Move file.",u'{F7}'),
    ("CopyFile","Copy file","Copy file.",u'{F8}'),
    ("DeleteFile","Delete file","Delete file.",u'{Del}'),
    ("SaveDialog","Show Save dialog","Show Save dialog.",u'{Ctrl+S}'),
    ("SaveAs",'Show "Save as" dialog','Show "Save as" dialog.',u'{S}'),
    ("PrintDialog","Show Print dialog","Show Print dialog.",u'{Ctrl+P}'),
    ("DirectPrint","Direct print","Print image, hide print dialog (direct print).",u'{Ctrl+Alt+P}'),
    ("AcquireBatchScanning","Acquire/Batch Scanning","Acquire/Batch Scanning",u'{Ctrl+Shift+A}'),
    ("CloseActualWindow","Close actual window","Close actual window (main window, slideshow, full screen, thumbnails or a dialog).",u'{Esc}'),
    ("SearchFiles","Search files","Search files.",u'{Ctrl+F}'),
),(
    ("EditUndo","Edit -> Undo","Edit -> Undo.",u'{Ctrl+Z}'),
    ("CreateSelection","Create custom selection","Edit -> Create custom selection.",u'{Shift+C}'),
    ("InsertText","Insert text into selection","Edit -> Insert text into selection.",u'{Ctrl+T}'),
    ("CutSelectionRectangle","Cut selection rectangle","Cut selection rectangle.",u'{Ctrl+X}'),
    ("CropSelectionRectangle","Crop selection rectangle","Crop selection rectangle.",u'{Ctrl+Y}'),
    ("CopyToClipboard","Copy image to clipboard","Copy image to clipboard.",u'{Ctrl+C}'),
#    ("PasteFromClipboard","Paste image from clipboard","Paste image from clipboard.",u'{Ins}'),
    ("PasteFromClipboard","Paste from clipboard","Paste image from clipboard.",u'{Ctrl+V}'),
    ("EditDelete","Edit -> Delete","Edit -> Delete.",u'{D}'),
),(
    ("ShowInformation","Show image information","Show image information.",u'{I}'),
    ("RotateLeft","Rotate left","Rotate left.",u'{L}'),
    ("RotateRight","Rotate right","Rotate right.",u'{R}'),
    ("RotateAngle","Rotate by angle","Rotate by angle.",u'{Ctrl+U}'),
    ("VerticalFlip","Vertical flip","Vertical flip.",u'{V}'),
    ("HorizontalFlip","Horizontal flip","Horizontal flip.",u'{H}'),
    ("ResampleDialog","Show Resample dialog","Show Resample dialog.",u'{Ctrl+R}'),
    ("EnhanceColors","Enhance colors","Enhance colors.",u'{Shift+G}'),
    ("AutoColorCorrection","Auto color correction","Auto color correction.",u'{Shift+U}'),
    ("Sharpen","Sharpen","Sharpen.",u'{Shift+S}'),
    ("RedEyeReduction","Red eye reduction","Red eye reduction.",u'{Shift+Y}'),
    ("EffectsSetup","Effects setup","Effects setup.",u'{Ctrl+E}'),
    ("AdobeFiltersDialog","Adobe 8BF filters dialog","Adobe 8BF filters dialog.",u'{Ctrl+K}'),
    ("FilterFactoryDialog","Filter Factory dialog","Filter Factory dialog.",u'{K}'),
    ("RotationLeft","Lossless JPG rot. Left","Lossless JPG rotation - to Left.",u'{Ctrl+Shift+L}'),
    ("RotationRight","Lossless JPG rot. Right","Lossless JPG rotation - to Right.",u'{Ctrl+Shift+R}'),
),(
    ("PropertiesDialog","Show Properties dialog","Show Properties dialog.",u'{P}'),
    ("StopAnimation","Stop animation","Stop GIF or ANI animation.",u'{G}'),
    ("ShowCommentDialog","Show Comment dialog JPGs","Show Comment dialog for JPGs.",u'{Ctrl+Shift+M}'),
    ("JpgLosslessOperations","JPG lossless operations","JPG lossless operations.",u'{Shift+J}'),
    ("CaptureDialog","Show Capture dialog","Show Capture dialog.",u'{C}'),
    ("MinimizeWindow","Minimize IrfanView window","Minimize IrfanView window - Boss key ;-).",u'{M}'),
    ("WallpaperCentered","Wallpaper centered","Set as wallpaper - centered.",u'{Ctrl+Shift+C}'),
    ("WallpaperTiled","Wallpaper tiled","Set as wallpaper - tiled.",u'{Ctrl+Shift+T}'),
    ("WallpaperStretched","Wallpaper stretched","Set as wallpaper - stretched.",u'{Ctrl+Shift+S}'),
    ("PreviousWallpaper","Previous wallpaper","Set as wallpaper - previous wallpaper.",u'{Ctrl+Shift+P}'),
),(
    ("ToggleStatusBar","Show/hide status bar","Show/hide status bar.",u'{Alt+Shift+S}'),
    ("ToggleToolbar","Show/hide toolbar","Show/hide toolbar.",u'{Alt+Shift+T}'),
    ("ToggleMenuBar","Show/hide menu bar","Show/hide menu bar.",u'{Alt+Shift+M}'),
    ("ToggleCaption","Show/hide caption","Show/hide caption.",u'{Alt+Shift+C}'),
    ("ToggleFit","Fit to desktop/Fit to image","Switch (toggle) between 'Fit images to desktop' and 'Fit window to image'.",u'{F}'),
    ("FullScreen","Full Screen","Full Screen.",u'{Enter}'),
    ("FullScreenMode1","Full screen mode 1:1","Full screen mode: Show images/movies with the original size (1:1).",u'{1}'),
    ("FullScreenMode2","Large fit to full screen","Full screen mode: Fit to screen: large images only.",u'{2}'),
    ("FullScreenMode3","All fit to full screen","Full screen mode: Fit to screen: all images/movies.",u'{3}'),
    ("FullScreenMode4","All stretch to full screen","Full screen mode: Stretch all images/movies to screen.",u'{4}'),
    ("LoadNextFile","Load next file","Load next file in directory.",u'{Space}'),
    ("LoadPrevFile","Load previous file","Load previous file in directory.",u'{Backspace}'),
    ("LoadFirstFile","Load first file","Load first file in the directory.",u'{Ctrl+Home}'),
    ("LoadLastFile","Load last file","Load last file in the directory.",u'{Ctrl+End}'),
    ("OpenRandomImage","Open random image","Open random image from the directory.",u'{Ctrl+M}'),
    ("Refresh","Refresh","Refresh (display and directory list).",u'{F5}'),
    ("ToggleAutSlideshow1","Start/stop automatic slideshow","Start/stop automatic viewing (slideshow in window).",u'{Shift+A}'),
    ("ZoomIn","Zoom In","Zoom In.",u'{Add}'),
    ("ZoomOut","Zoom Out","Zoom Out.",u'{Subtract}'),
    ("ToggleLockZoom","Lock/unlock zoom","Lock/unlock zoom (also in full screen mode).",u'{Shift+L}'),
    ("OriginalSize","Original size","Original size (no zoom).",u'{Ctrl+H}'),
    ("ShowInHexViewer","Show in HEX viewer","Show image in HEX viewer.",u'{F3}'),
    ("EditMultipageTif","Edit multipage TIF","Edit multipage TIF.",u'{Ctrl+Q}'),
    ("ShowNextPgOrFile","Show next page OR file","Show next page in a multipage image OR load next file in directory.",u'{Ctrl+PgDown}'),
    ("ShowPrevPgOrFile","Show previous page OR file","Show previous page in a multipage image OR load previous file in directory.",u'{Ctrl+PgUp}'),
    ("ScrollImageUp","Scroll image up","Scroll image up.",u'{Up}'),
    ("ScrollImageDown","Scroll image down","Scroll image down.",u'{Down}'),
    ("ScrollRightOrNext","Scroll right OR next image","Scroll image right OR next image in directory.",u'{Right}'),
    ("ScrollLeftOrPrevious","Scroll left OR previous","Scroll image left OR previous image in directory.",u'{Left}'),
    ("ScrollUpOrPrevious","Scroll up OR previous file","Load previous file in directory OR scroll image up.",u'{PgUp}'),
    ("ScrollDownOrNext","Scroll down OR next file","Load next file in directory OR scroll image down.",u'{PgDown}'),
    ("ScrollToBeginOrFirstFile","Scroll to begin OR load first file","Scroll to begin (horizontal scroll) OR load first file in directory.",u'{Home}'),
    ("ScrollToEndOrLastFile","Scroll to end OR load last file","Scroll to end (horizontal scroll) OR load last file in directory.",u'{End}'),
),(
    ("ToggleAutSlideshow2","Pause/Resume automatic slideshow","Pause an automatic slideshow. Press this key again to resume the slideshow.",u'{Pause}'),
    ("AppendToSlideshow","Append to current slideshow","Append current file to current slideshow.",u'{F4}'),
    ("ToggleSlideshow","Fullscreen/Slideshow text display","Toggle fullscreen/slideshow text display.",u'{N}'),
    ("StartDirSlideshow","Start directory slideshow","Start slideshow with current directory files.",u'{Ctrl+W}'),
    ("ShowExifDialog","Show EXIF dialog","Show EXIF dialog for JPGs with available EXIF data.",u'{E}'),
    ("ControlSwitchThumb","Control switch in thumb. wind.","Control switch in the thumbnail window.",u'{Ctrl+Tab}'),
    ("SwitchMainThumbnail","Switch main/thumbnail window","Switch between main and thumbnail window (if visible).",u'{Tab}'),
    ("SelectAllThumb","Select all thumbnails","Select all thumbnails (thumbnail window).",u'{Ctrl+A}'),
    ("OpenBrowseDialog",'Show "Browse-Subfolders" dialog.','Show "Browse-Subfolders" dialog.',u'{Ctrl+B}'),
    ("ShowIptcDialog","Show IPTC dialog","Show IPTC dialog for JPGs.",u'{Ctrl+I}'),
    ("SendByMail","Send image by email","Send image by email.",u'{Shift+M}'),
    ("CopyFilename","Copy filename to clipboard.","Copy current filename to clipboard.",u'{Shift+P}'),
    ("JumpIntoToolbar","Jump into toolbar edit field","Jump into the toolbar edit field.",u'{Shift+T}'),
    ("Help","Help","Help.",u'{F1}'),
    ("AboutIrfanView",'Show "About IrfanView" dialog','Show "About IrfanView" dialog.',u'{A}'),
)))
