# -*- coding: utf-8 -*-
#
# This file is part of EventGhost.
# Copyright Â© 2005-2016 EventGhost Project <http://www.eventghost.org/>
#
# EventGhost is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 2 of the License, or (at your option)
# any later version.
#
# EventGhost is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with EventGhost. If not, see <http://www.gnu.org/licenses/>.

# - 0.1c by topix
#   added detection of 64it installation of J. River Media center

import eg

eg.RegisterPlugin(
    name=u'JRiver Command Sender',
    author=u'K',
    version=u'0.1c',
    description=(
        u'Sends commands to JRiver Media Center without the use of emulated '
        u'keystrokes'
    ),
    kind=u'program',
    url=u'',
    help=u'',
    canMultiLoad=False,
    createMacrosOnAdd=True,
    guid=u'{D355EBBF-3631-47E2-BC44-64A928B9F271}',
    hardwareId=u'',
    icon=None
)


import wx
import _winreg
from subprocess import Popen, PIPE
from threading import Thread


DEBUG = False

MCC_PLAY_PAUSE = 10000
MCC_PLAY = 10001
MCC_STOP = 10002
MCC_STOP_DISPLAY_ERROR = 10002
MCC_NEXT = 10003
MCC_NEXT_NO_CHAPTERS = 10003
MCC_PREVIOUS = 10004
MCC_SHUFFLE_TOGGLE = 10005
MCC_SHUFFLE_JUMP = 10005
MCC_SHUFFLE_NO_JUMP = 10005
MCC_SHUFFLE_SET_MODE = 10005
MCC_CONTINUOUS_TOGGLE = 10006
MCC_CONTINUOUS_OFF = 10006
MCC_CONTINUOUS_PLAYLIST = 10006
MCC_CONTINUOUS_SONG = 10006
MCC_CONTINUOUS_STOP_AFTER_EACH = 10006
MCC_FAST_FORWARD = 10008
MCC_REWIND = 10009
MCC_STOP_CONDITIONAL = 10010
MCC_SET_ZONE_NEXT = 10011
MCC_SET_ZONE_PREVIOUS = 10011
MCC_TOGGLE_DISPLAY = 10012
MCC_TOGGLE_DISPLAY_NO_THEATER_VIEW = 10012
MCC_SHOW_WINDOW = 10013
MCC_SHOW_WINDOW_NOW_PLAYING = 10013
MCC_MINIMIZE_WINDOW = 10014
MCC_PLAY_CPLDB_INDEX = 10015
MCC_SHOW_DSP_STUDIO = 10016
MCC_VOLUME_MUTE_TOGGLE = 10017
MCC_VOLUME_MUTE_ON = 10017
MCC_VOLUME_MUTE_OFF = 10017
MCC_VOLUME_UP = 10018
MCC_VOLUME_DOWN = 10019
MCC_VOLUME_SET = 10020
MCC_SHOW_PLAYBACK_OPTIONS = 10021
MCC_SET_PAUSE_TOGGLE = 10022
MCC_SET_PAUSE_ON = 10022
MCC_SET_PAUSE_OFF = 10022
MCC_SET_CURRENTLY_PLAYING_RATING = 10023
MCC_SHOW_PLAYBACK_ENGINE_MENU = 10024
MCC_PLAY_NEXT_PLAYLIST = 10025
MCC_PLAY_PREVIOUS_PLAYLIST = 10026
MCC_MAXIMIZE_WINDOW = 10027
MCC_RESTORE_WINDOW = 10028
MCC_SET_PLAYERSTATUS = 10029
MCC_SET_ALTERNATE_PLAYBACK_SETTINGS_TOGGLE = 10030
MCC_SET_ALTERNATE_PLAYBACK_SETTINGS_ON = 10030
MCC_SET_ALTERNATE_PLAYBACK_SETTINGS_OFF = 10030
MCC_SET_PREVIEW_MODE_SETTINGS = 10031
MCC_SHOW_PLAYBACK_ENGINE_DISPLAY_PLUGIN_MENU = 10032
MCC_DVD_MENU = 10033
MCC_SEEK_FORWARD = 10034
MCC_SEEK_BACK = 10035
MCC_STOP_AFTER_CURRENT_FILE_TOGGLE = 10036
MCC_STOP_AFTER_CURRENT_FILE_ON = 10036
MCC_STOP_AFTER_CURRENT_FILE_OFF = 10036
MCC_DETACH_DISPLAY_TOGGLE = 10037
MCC_DETACH_DISPLAY_ON = 10037
MCC_DETACH_DISPLAY_OFF = 10037
MCC_SET_MODE_ZONE_SPECIFIC = 10038
MCC_STOP_INTERNAL = 10039
MCC_PLAYING_NOW_REMOVE_DUPLICATES = 10040
MCC_SHUFFLE_REMAINING = 10041
MCC_PLAY_FIRST_FILE = 10042
MCC_PLAY_LAST_FILE = 10043
MCC_PLAY_FILE_BY_STRING = 10044
MCC_PLAY_FILE_AGAIN = 10045
MCC_HANDLE_PLAYBACK_ERROR = 10046
MCC_PLAY_AUTOMATIC_PLAYLIST = 10047
MCC_SEEK = 10048
MCC_CLEAR_PLAYING_NOW_ZONE_SPECIFIC_ALL = 10049
MCC_CLEAR_PLAYING_NOW_ZONE_SPECIFIC_LEAVE_PLAYING = 10049
MCC_PLAY_RADIO_LAST_FM = 10050
MCC_SHOW_ON_SCREEN_DISPLAY = 10051
MCC_SET_SUBTITLES = 10052
MCC_SET_SUBTITLES_PREVIOUS = 10052
MCC_SET_SUBTITLES_NEXT = 10052
MCC_SET_AUDIO_STREAM = 10053
MCC_SET_AUDIO_STREAM_PREVIOUS = 10053
MCC_SET_AUDIO_STREAM_NEXT = 10053
MCC_SET_VIDEO_STREAM = 10054
MCC_SET_VIDEO_STREAM_PREVIOUS = 10054
MCC_SET_VIDEO_STREAM_NEXT = 10054
MCC_VIDEO_SCREEN_GRAB_THUMBNAIL = 10055
MCC_VIDEO_SCREEN_GRAB_SAVE = 10055
MCC_SET_VOLUME_MODE_APPLICATION = 10056
MCC_SET_VOLUME_MODE_INTERNAL = 10056
MCC_SET_VOLUME_MODE_SYSTEM = 10056
MCC_SET_VOLUME_MODE_DISABLED = 10056
MCC_RESTART_PLAYBACK = 10057
MCC_ZONE_SWITCH = 10058
MCC_SKIP_TO = 10059
MCC_LINK_ZONE = 10060
MCC_UNLINK_ZONE = 10061
MCC_PLAY_RADIO_MEDIANET = 10062
MCC_CLEAR_PLAYED_ZONE_SPECIFIC = 10063
MCC_OPEN_FILE = 20000
MCC_OPEN_URL = 20001
MCC_PRINT_LIST = 20002
MCC_EXPORT_PLAYLIST_ACTIVE = 20003
MCC_EXPORT_PLAYLIST = 20003
MCC_EXPORT_ALL_PLAYLISTS = 20004
MCC_EXPORT_ALL_PLAYLISTS_SILENT = 20004
MCC_UPLOAD_FILES = 20005
MCC_EMAIL_FILES = 20006
MCC_EXIT = 20007
MCC_EXIT_CLOSE_SERVER = 20007
MCC_EXIT_ALLOW_SERVER = 20007
MCC_UPDATE_LIBRARY = 20008
MCC_CLEAR_LIBRARY = 20009
MCC_EXPORT_LIBRARY = 20010
MCC_BACKUP_LIBRARY = 20011
MCC_BACKUP_LIBRARY_SILENT = 20011
MCC_RESTORE_LIBRARY = 20012
MCC_LIBRARY_MANAGER = 20013
MCC_IMAGE_ACQUIRE = 20014
MCC_PRINT_IMAGES = 20015
MCC_PRINT = 20016
MCC_IMPORT_PLAYLIST = 20024
MCC_LOAD_LIBRARY = 20025
MCC_SYNC_LIBRARY = 20026
MCC_EMAIL_PODCAST_FEED = 20027
MCC_LOAD_LIBRARY_READ_ONLY = 20028
MCC_ADD_LIBRARY = 20029
MCC_EXPORT_ITUNES = 20030
MCC_DISCONNECT_LIBRARY = 20031
MCC_SYNC_WITH_LIBRARY_SERVER = 20032
MCC_STOP_ALL_ZONES = 20033
MCC_STOP_REMOTE_ZONES = 20033
MCC_CLONE_LIBRARY = 20034
MCC_OPEN_LIVE = 20035
MCC_COPY = 21000
MCC_PASTE = 21001
MCC_SELECT_ALL = 21002
MCC_SELECT_INVERT = 21003
MCC_DELETE = 21004
MCC_DELETE_AGGRESSIVE = 21004
MCC_RENAME = 21005
MCC_UNDO = 21006
MCC_REDO = 21007
MCC_QUICK_SEARCH = 21008
MCC_REPEAT_SEARCH = 21008
MCC_ADD_PLAYLIST = 21009
MCC_ADD_SMARTLIST = 21010
MCC_ADD_PLAYLIST_GROUP = 21011
MCC_PROPERTIES = 21012
MCC_TOGGLE_TAGGING_MODE = 21013
MCC_CUT = 21014
MCC_DESELECT_ALL = 21015
MCC_DELETE_ALL = 21016
MCC_DELETE_ALL_AGGRESSIVE = 21016
MCC_ADD_PODCAST_FEED = 21017
MCC_EDIT_PODCAST_FEED = 21018
MCC_ADD_PODCAST_DEFAULTS = 21019
MCC_CREATE_STOCK_SMARTLISTS = 21020
MCC_ENABLE_PODCAST_DOWNLOAD = 21021
MCC_DISABLE_PODCAST_DOWNLOAD = 21022
MCC_EDIT_PLAYLIST = 21023
MCC_EDIT_PLAYING_NOW = 21024
MCC_EDIT_DISC_INFORMATION = 21025
MCC_EDIT_SMARTLIST = 21026
MCC_REFRESH_PODCAST_FEED = 21027
MCC_LOOKUP_MOVIE_INFORMATION = 21028
MCC_ADD_ZONE = 21029
MCC_ADD_AUTOMATIC_PLAYLIST = 21030
MCC_SET_WRITE_TAGS_TOGGLE = 21031
MCC_SET_WRITE_TAGS_ON = 21031
MCC_SET_WRITE_TAGS_OFF = 21031
MCC_PASTE_TAGS = 21032
MCC_SHUFFLE_SELECTION = 21033
MCC_TOGGLE_MODE = 22000
MCC_TOGGLE_MODE_NEXT = 22000
MCC_THEATER_VIEW = 22001
MCC_PARTY_MODE = 22002
MCC_SHOW_TREE_ROOT = 22003
MCC_FIND_MEDIA = 22004
MCC_BACK = 22005
MCC_FORWARD = 22006
MCC_REFRESH = 22007
MCC_SET_LIST_STYLE = 22008
MCC_SET_LIST_STYLE_TOGGLE = 22008
MCC_SET_MODE = 22009
MCC_SHOW_RECENTLYIMPORTED = 22012
MCC_SHOW_TOPHITS = 22013
MCC_SHOW_RECENTLYPLAYED = 22014
MCC_SET_MEDIA_MODE = 22015
MCC_SET_SERVER_MODE_ON = 22017
MCC_SET_SERVER_MODE_OFF = 22017
MCC_SET_MODE_FOR_EXTERNAL_PROGRAM_STARTING = 22018
MCC_SET_MODE_FOR_EXTERNAL_PROGRAM_ENDING = 22018
MCC_SET_MODE_FOR_SECOND_INSTANCE_LAUNCH = 22019
MCC_HOME = 22020
MCC_ROLLUP_VIEW_HEADER_TOGGLE = 22021
MCC_ROLLUP_VIEW_HEADER_ON = 22021
MCC_ROLLUP_VIEW_HEADER_OFF = 22021
MCC_FOCUS_SEARCH_CONTROL = 22022
MCC_SET_ACTIVE_VIEW_KEY_TOGGLE = 22023
MCC_SET_ACTIVE_VIEW_KEY_TOGGLE_BACK = 22023
MCC_SET_ACTIVE_VIEW_KEY_NEW = 22023
MCC_SET_ACTIVE_VIEW_KEY = 22023
MCC_CLOSE_VIEW_KEY = 22024
MCC_CLOSE_VIEW_KEY_CURRENT = 22024
MCC_VIEW_ZOOM_SET = 22025
MCC_VIEW_ZOOM_INCREMENT = 22026
MCC_FIND_MEDIA_WITH_WIZARD = 22027
MCC_SET_USER = 22028
MCC_SHOW_TREE_TOGGLE = 22029
MCC_SHOW_TREE_ON = 22029
MCC_SHOW_TREE_OFF = 22029
MCC_SET_TOOLTIPS_TOGGLE = 22030
MCC_SET_TOOLTIPS_ON = 22030
MCC_SET_TOOLTIPS_OFF = 22030
MCC_AUDIO_ONLY_MODE_TOGGLE = 22031
MCC_AUDIO_ONLY_MODE_ON = 22031
MCC_AUDIO_ONLY_MODE_OFF = 22031
MCC_IMPORT_DISABLE_RUNNING_WARNING = 23000
MCC_IMPORT_FIRST_IMPORT_MODE = 23000
MCC_RIP_CD = 23001
MCC_BURN = 23002
MCC_RECORD_AUDIO = 23003
MCC_CONVERT = 23004
MCC_ANALYZE_AUDIO = 23005
MCC_MEDIA_EDITOR = 23006
MCC_CD_LABELER = 23007
MCC_SKIN_MANAGER = 23010
MCC_OPTIONS = 23011
MCC_RENAME_CD_FILES = 23012
MCC_HANDHELD_UPLOAD = 23015
MCC_HANDHELD_UPDATE_UPLOAD_WORKER_FINISHED = 23016
MCC_HANDHELD_CLOSE_DEVICE = 23017
MCC_HANDHELD_SHOW_OPTIONS = 23018
MCC_HANDHELD_INFO_DUMP_ON = 23019
MCC_HANDHELD_INFO_DUMP_OFF = 23019
MCC_IMPORT_AUTO_RUN_NOW = 23020
MCC_IMPORT_AUTO_RUN_NOW_SILENT = 23020
MCC_IMPORT_AUTO_CONFIGURE = 23021
MCC_HANDHELD_EJECT = 23022
MCC_RECORD_TV = 23023
MCC_FIND_AND_REPLACE = 23024
MCC_CLEAN_PROPERTIES = 23025
MCC_FILL_TRACK_ORDER = 23026
MCC_MOVE_COPY_FIELDS = 23027
MCC_REMOVE_TAGS = 23028
MCC_UPDATE_TAGS_FROM_DB = 23029
MCC_UPDATE_DB_FROM_TAGS = 23030
MCC_LOOKUP_TRACK_INFO_FROM_INTERNET = 23031
MCC_SUBMIT_TRACK_INFO_TO_INTERNET = 23032
MCC_FILL_PROPERTIES_FROM_FILENAME = 23034
MCC_RENAME_FILES_FROM_PROPERTIES = 23035
MCC_COVER_ART_ADD_FROM_FILE = 23036
MCC_COVER_ART_QUICK_ADD_FROM_FILE = 23037
MCC_COVER_ART_GET_FROM_INTERNET = 23038
MCC_COVER_ART_SUBMIT_TO_INTERNET = 23039
MCC_COVER_ART_GET_FROM_SCANNER = 23040
MCC_COVER_ART_SELECT_SCANNER = 23041
MCC_COVER_ART_GET_FROM_CLIPBOARD = 23042
MCC_COVER_ART_COPY_TO_CLIPBOARD = 23043
MCC_COVER_ART_REMOVE = 23044
MCC_COVER_ART_PLAY = 23045
MCC_COVER_ART_SAVE_TO_EXTERNAL_FILE = 23046
MCC_COVER_ART_REBUILD_THUMBNAIL = 23047
MCC_RINGTONE = 23048
MCC_AUDIO_CALIBRATION = 23049
MCC_MARK_PLAYED = 23050
MCC_MARK_NOT_PLAYED = 23051
MCC_LINK_TRACKS = 23052
MCC_BREAK_TRACK_LINKS = 23053
MCC_HELP_CONTENTS = 24000
MCC_HELP_HOWTO_IMPORT_FILES = 24001
MCC_HELP_HOWTO_PLAY_FILES = 24002
MCC_HELP_HOWTO_RIP = 24003
MCC_HELP_HOWTO_BURN = 24004
MCC_HELP_HOWTO_ORGANIZE_FILES = 24005
MCC_HELP_HOWTO_VIEW_SCHEMES = 24006
MCC_HELP_HOWTO_MANAGE_PLAYLISTS = 24007
MCC_HELP_HOWTO_EDIT_PROPERTIES = 24008
MCC_HELP_HOWTO_FIND = 24009
MCC_HELP_HOWTO_CONFIGURE = 24010
MCC_CHECK_FOR_UPDATES = 24011
MCC_BUY = 24012
MCC_INSTALL_LICENSE = 24013
MCC_REGISTRATION_INFO = 24014
MCC_PLUS_FEATURES = 24015
MCC_INTERACT = 24016
MCC_SYSTEM_INFO = 24017
MCC_ABOUT = 24018
MCC_CONFIGURE_DEBUG_LOGGING = 24019
MCC_WIKI = 24020
MCC_TEST = 24021
MCC_SHOW_EULA = 24022
MCC_BENCHMARK = 24023
MCC_UPGRADE_TO_MASTER_LICENSE = 24024
MCC_ADD_VIEW_SCHEME = 25000
MCC_EDIT_VIEW_SCHEME = 25001
MCC_TREE_ADD_DIRECTORY = 25008
MCC_TREE_IMPORT = 25009
MCC_TREE_ADD_CD_FOLDER = 25010
MCC_UPDATE_FROM_CD_DATABASE = 25011
MCC_SUBMIT_TO_CD_DATABASE = 25012
MCC_TREE_RIP = 25013
MCC_CLEAR_PLAYING_NOW = 25014
MCC_CLEAR_PLAYING_NOW_LEAVE_PLAYING = 25014
MCC_COPY_LISTENING_TO = 25015
MCC_COPY_LISTENING_TO_PASTE = 25015
MCC_TREE_SET_EXPANDED = 25016
MCC_TREE_SET_COLLAPSED = 25016
MCC_RESET_VIEW_SCHEMES = 25017
MCC_TREE_ERASE_CD_DVD = 25018
MCC_UPDATE_FROM_CDPLAYER_INI = 25019
MCC_TREE_EJECT = 25020
MCC_TREE_ADD_VIRTUAL_DEVICE = 25021
MCC_TREE_RENAME_PLAYLIST = 25022
MCC_TWITTER_LISTENING_TO = 25023
MCC_SCROBBLE_LISTENING_TO = 25024
MCC_LIST_UPDATE_ORDER = 26000
MCC_LIST_SHUFFLE_ORDER = 26001
MCC_LIST_IMPORT = 26002
MCC_LIST_REMOVE_ORDER = 26003
MCC_LOCATE_FILE_DISK_INTERNAL = 26004
MCC_LOCATE_FILE_DISK_EXTERNAL = 26004
MCC_LOCATE_FILE = 26004
MCC_LIST_INCREMENT_SELECTION = 26006
MCC_LIST_REMOVE_DUPLICATES = 26007
MCC_LIST_AUTO_SIZE_COLUMN = 26008
MCC_LIST_AUTO_SIZE_COLUMN_ALL = 26008
MCC_LIST_CUSTOMIZE_VIEW = 26009
MCC_LIST_COPY_DISK_FILES = 26010
MCC_LIST_SET_RIP_CHECK_TOGGLE = 26011
MCC_LIST_SET_RIP_CHECK_ON = 26011
MCC_LIST_SET_RIP_CHECK_OFF = 26011
MCC_LIST_DOWNLOAD = 26012
MCC_LIST_GET_LIST_POINTER = 26013
MCC_LOCATE_STACK = 26014
MCC_SET_AS_STACK_TOP = 26015
MCC_EXPAND_STACK = 26016
MCC_COLLAPSE_STACK = 26017
MCC_AUTOSTACK_NAME = 26018
MCC_AUTOSTACK_ARTIST_ALBUM_NAME = 26018
MCC_AUTOSTACK_ARTIST_ALBUM_TRACK = 26018
MCC_CHECK_STACKS = 26019
MCC_STACK = 26020
MCC_UNSTACK = 26021
MCC_ADD_TO_STACK = 26022
MCC_PANE_RESET_SELECTION = 26023
MCC_PANE_RESET_SELECTION_ALL = 26023
MCC_LIST_REMOVE_ALL = 26024
MCC_LIST_LOCK_TOGGLE = 26025
MCC_LIST_LOCK_ON = 26025
MCC_LIST_LOCK_OFF = 26025
MCC_PANE_SET_EXPANDED = 26026
MCC_KEYSTROKE = 27000
MCC_PC_SHUTDOWN = 27001
MCC_PC_HIBERNATE = 27001
MCC_PC_SLEEP = 27001
MCC_PC_RESTART = 27001
MCC_PLAYBACK_ENGINE_ZOOM_IN = 28000
MCC_PLAYBACK_ENGINE_ZOOM_OUT = 28001
MCC_PLAYBACK_ENGINE_UP = 28002
MCC_PLAYBACK_ENGINE_DOWN = 28003
MCC_PLAYBACK_ENGINE_LEFT = 28004
MCC_PLAYBACK_ENGINE_RIGHT = 28005
MCC_PLAYBACK_ENGINE_ENTER = 28006
MCC_PLAYBACK_ENGINE_FIRST = 28007
MCC_PLAYBACK_ENGINE_LAST = 28008
MCC_PLAYBACK_ENGINE_NEXT = 28009
MCC_PLAYBACK_ENGINE_PREVIOUS = 28010
MCC_PLAYBACK_ENGINE_PAUSE_TOGGLE = 28011
MCC_PLAYBACK_ENGINE_PAUSE_ON = 28011
MCC_PLAYBACK_ENGINE_PAUSE_OFF = 28011
MCC_IMAGE_PAN_AND_ZOOM_TOGGLE = 28012
MCC_IMAGE_PAN_AND_ZOOM_ON = 28012
MCC_IMAGE_PAN_AND_ZOOM_OFF = 28012
MCC_IMAGE_TOGGLE_EFFECT = 28013
MCC_IMAGE_RAPID_ZOOM = 28014
MCC_DVD_SET_AUDIO_STREAM_TOGGLE = 28015
MCC_DVD_SET_AUDIO_STREAM = 28015
MCC_DVD_SHOW_MENU = 28016
MCC_TV_RECORD = 28017
MCC_TV_SNAPSHOT = 28018
MCC_TV_CHANGE_STANDARD = 28019
MCC_PLAYBACK_ENGINE_OSD_VIDEO_PROC_AMP = 28020
MCC_PLAYBACK_ENGINE_SET_CUR_VIDEO_PROC_AMP = 28021
MCC_PLAYBACK_ENGINE_SET_ASPECT_RATIO_TOGGLE = 28022
MCC_PLAYBACK_ENGINE_SET_ASPECT_RATIO = 28022
MCC_PLAYBACK_ENGINE_SCROLL_UP = 28023
MCC_PLAYBACK_ENGINE_SCROLL_DOWN = 28024
MCC_PLAYBACK_ENGINE_SCROLL_LEFT = 28025
MCC_PLAYBACK_ENGINE_SCROLL_RIGHT = 28026
MCC_TV_SET_SAVE_TIME_SHIFTING_INCREASE = 28027
MCC_TV_SET_SAVE_TIME_SHIFTING_DECREASE = 28027
MCC_TV_SET_SAVE_TIME_SHIFTING = 28027
MCC_PLAYBACK_ENGINE_ZOOM_TO_PRESET_FIT = 28028
MCC_PLAYBACK_ENGINE_ZOOM_TO_PRESET_100 = 28028
MCC_PLAYBACK_ENGINE_ZOOM_TO_PRESET_200 = 28028
MCC_TV_SCAN_PROGRAMMING_EVENTS = 28029
MCC_TV_CHANGE_CHANNEL_KEY = 28030
MCC_TV_PLAY_CHANNEL_POSITION = 28031
MCC_PLAYBACK_ENGINE_SET_SUBTITLES_NEXT = 28032
MCC_PLAYBACK_ENGINE_SET_SUBTITLES_PREVIOUS = 28032
MCC_PLAYBACK_ENGINE_SET_SUBTITLES = 28032
MCC_PLAYBACK_ENGINE_SET_AUDIO_STREAM_NEXT = 28033
MCC_PLAYBACK_ENGINE_SET_AUDIO_STREAM_PREVIOUS = 28033
MCC_PLAYBACK_ENGINE_SET_AUDIO_STREAM = 28033
MCC_PLAYBACK_ENGINE_SET_VIDEO_STREAM_NEXT = 28034
MCC_PLAYBACK_ENGINE_SET_VIDEO_STREAM_PREVIOUS = 28034
MCC_PLAYBACK_ENGINE_SET_VIDEO_STREAM = 28034
MCC_PLAYBACK_ENGINE_VIDEO_SCREEN_GRAB_THUMBNAIL = 28035
MCC_PLAYBACK_ENGINE_VIDEO_SCREEN_GRAB_SAVE = 28035
MCC_PLAYBACK_ENGINE_VIDEO_LIPSYNC = 28036
MCC_PLAYBACK_ENGINE_SET_SUBTITLE_TIMING = 28037
MCC_RELOAD_MC_VIEW = 30000
MCC_CUSTOMIZE_TOOLBAR = 30001
MCC_PLAY_TV = 30002
MCC_UPDATE_WEBPAGES = 30003
MCC_SHOW_RUNNING_MC_ON = 30004
MCC_SHOW_RUNNING_MC_OFF = 30004
MCC_SHOW_MENU = 30005
MCC_TUNE_TV = 30006
MCC_PLAY_PLAYLIST = 30007
MCC_SENDTO_TOOL_LABELER = 30008
MCC_SENDTO_TOOL_MEDIA_EDITOR = 30008
MCC_SENDTO_TOOL_DEFAULT_EDITOR = 30008
MCC_SENDTO_TOOL_FTP = 30008
MCC_SENDTO_TOOL_EMAIL = 30008
MCC_SENDTO_TOOL_MENALTO_GALLERY = 30008
MCC_SENDTO_TOOL_WEB_GALLERY = 30008
MCC_CONFIGURE_THEATER_VIEW = 30012
MCC_SET_STATUSTEXT = 30013
MCC_UPDATE_UI_AFTER_ACTIVE_WINDOW_CHANGE = 30014
MCC_REENUM_PORTABLE_DEVICES = 30015
MCC_REENUM_PORTABLE_DEVICES_CONNECTED = 30015
MCC_PLAY_ADVANCED = 30016
MCC_UPDATE_STATUS_BAR = 30017
MCC_REQUEST_PODCAST_UPDATE = 30018
MCC_REQUEST_PODCAST_PURGE = 30019
MCC_SHOW_INVALID_CD_VOLUME_WARNING = 30021
MCC_PLAY_TV_CHANNEL_FOR_CLIENT = 30022
MCC_STOP_SERVING_TV_FILE = 30023
MCC_SHOW_DEVICE_PRESENTATION_WEBPAGE = 30024
MCC_IMAGE_SET_DESKTOP_BACK = 31000
MCC_IMAGE_ROTATE_LEFT = 31001
MCC_IMAGE_ROTATE_RIGHT = 31002
MCC_IMAGE_ROTATE_UPSIDEDOWN = 31003
MCC_IMAGE_RESIZE = 31004
MCC_IMAGE_EDIT = 31005
MCC_IMAGE_DELETE = 31006
MCC_IMAGE_PREVIEW_SHOW = 31007
MCC_IMAGE_PREVIEW_HIDE = 31008
MCC_IMAGE_LOCATE_ON_MAP = 31009
MCC_QUERY_UI_MODE = 32000
MCC_GET_SELECTED_FILES = 33000
MCC_PRINTVIEW = 33001
MCC_OUTPUT = 33002
MCC_OUTPUT_ACTIVE_VIEW = 33002
MCC_SETFOCUS = 33003
MCC_SELECT_FILES = 33004
MCC_DOUBLE_CLICK = 33005
MCC_PLAY_OR_SHOW = 33006
MCC_SHOW_CURRENT_FILE_FORCE = 33007
MCC_SHOW_CURRENT_FILE_SELECT = 33007
MCC_BUY_SELECTED_TRACKS = 33008
MCC_BUY_ALL_TRACKS = 33009
MCC_BUY_ALBUM = 33010
MCC_UPDATE_AFTER_PLUGIN_INSTALLED = 33011
MCC_UPDATE_AFTER_SKIN_INSTALLED = 33012
MCC_UPDATE_AFTER_SKIN_INSTALLED_MINIVIEW = 33012
MCC_NOTIFY_UI_CHANGED = 34000
MCC_NOTIFY_VIEW_CHANGED = 34001
MCC_NOTIFY_BEFORE_ACTIVE_VIEW_CHANGED = 34002
MCC_NOTIFY_ACTIVE_VIEW_CHANGED = 34003
MCC_NOTIFY_PLAYER_INFO_CHANGED = 34004
MCC_NOTIFY_TOOLTIPS_CHANGED_ON = 34005
MCC_NOTIFY_TOOLTIPS_CHANGED_OFF = 34005
MCC_NOTIFY_OPTIONS_CHANGED = 34006
MCC_UPDATE = 34007
MCC_NOTIFY_FOCUS_CHANGED = 34008
MCC_SAVE_PROPERTIES = 34009
MCC_NOTIFY_UI_MODE_CHANGED = 34010
MCC_NOTIFY_SELECTION_CHANGED = 34011
MCC_NOTIFY_FILE_CHANGED_INVALIDATE_ALL = 34012
MCC_NOTIFY_FILE_CHANGED = 34012
MCC_NOTIFY_FILE_STATUS_CHANGED_INVALIDATE_ALL = 34013
MCC_NOTIFY_FILE_STATUS_CHANGED = 34013
MCC_NOTIFY_FILE_ENSURE_VISIBLE = 34014
MCC_NOTIFY_GET_TAB_HWNDS = 34015
MCC_NOTIFY_BURNER_QUEUE_CHANGED = 34016
MCC_NOTIFY_BURNER_PROGRESS_CHANGED = 34017
MCC_NOTIFY_BURNER_STATUS_CHANGED = 34018
MCC_NOTIFY_BURNER_STARTED = 34019
MCC_NOTIFY_BURNER_FINISHED_INTERNAL = 34020
MCC_NOTIFY_BURNER_FINISHED = 34021
MCC_NOTIFY_BURNER_FAILED_INTERNAL = 34022
MCC_NOTIFY_BURNER_FAILED = 34023
MCC_NOTIFY_BURNER_CLOSE_UI = 34024
MCC_NOTIFY_BURNER_PREPARE_FOR_NEXT_COPY = 34025
MCC_NOTIFY_RIP_STARTED = 34026
MCC_NOTIFY_RIP_FINISHED = 34027
MCC_NOTIFY_RIP_FAILED = 34028
MCC_NOTIFY_RIP_PROGRESS_CHANGED = 34029
MCC_NOTIFY_RIP_QUEUE_CHANGED = 34030
MCC_NOTIFY_DVD_RIP_STARTED = 34031
MCC_NOTIFY_DVD_RIP_FINISHED = 34032
MCC_NOTIFY_DVD_RIP_FAILED = 34033
MCC_NOTIFY_DVD_RIP_PROGRESS_CHANGED = 34034
MCC_NOTIFY_DOWNLOAD_FINISHED = 34035
MCC_NOTIFY_DOWNLOAD_FINISHED_UNKNOWN = 34035
MCC_NOTIFY_DOWNLOAD_FAILED = 34036
MCC_NOTIFY_DOWNLOAD_FAILED_UNKNOWN = 34036
MCC_NOTIFY_DOWNLOAD_STATUS_CHANGED = 34037
MCC_NOTIFY_STATUS_CHECKER_COMPLETE = 34038
MCC_NOTIFY_CURRENT_ZONE_CHANGED = 34039
MCC_NOTIFY_DISPLAY_OWNER_CHANGED = 34040
MCC_NOTIFY_AFTER_FIRST_UPDATE_LAYOUT_WINDOW = 34041
MCC_NOTIFY_AFTER_FIRST_UPDATE_APPLY_VIEW_STATE = 34042
MCC_NOTIFY_PROCESS_TIME_REMAINING = 34043
MCC_NOTIFY_UI_UPDATE_ENABLE_DISABLE_STATES = 34044
MCC_UPDATE_WINDOW_LAYOUT = 34046
MCC_NOTIFY_SAVE_UI_BEFORE_SHUTDOWN = 34047
MCC_NOTIFY_PLAYLIST_FILES_CHANGED = 34049
MCC_NOTIFY_PLAYLIST_INFO_CHANGED = 34050
MCC_NOTIFY_PLAYLIST_ADDED_INTERNAL = 34051
MCC_NOTIFY_PLAYLIST_ADDED_BY_USER = 34052
MCC_NOTIFY_PLAYLIST_REMOVED = 34053
MCC_NOTIFY_PLAYLIST_COLLECTION_CHANGED = 34054
MCC_NOTIFY_PLAYLIST_PROPERTIES_CHANGED = 34055
MCC_NOTIFY_HANDHELD_UPLOAD_STARTED = 34056
MCC_NOTIFY_HANDHELD_AFTER_DEVICE_CHANGED = 34057
MCC_NOTIFY_HANDHELD_QUEUE_CHANGED = 34058
MCC_NOTIFY_HANDHELD_INFO_COMPLETE = 34059
MCC_NOTIFY_HANDHELD_AFTER_UPLOAD_FINISHED = 34060
MCC_NOTIFY_COMPACT_MEMORY = 34061
MCC_NOTIFY_SEARCH_CHANGED = 34062
MCC_NOTIFY_SEARCH_CONTEXT_CHANGED = 34063
MCC_NOTIFY_UPDATE_SHOPPING_CART = 34064
MCC_NOTIFY_UPDATE_NAVIGATION_TRAIL = 34065
MCC_NOTIFY_IMPORT_STARTED = 34066
MCC_NOTIFY_IMPORT_STARTED_SILENT = 34066
MCC_NOTIFY_IMPORT_FINISHED = 34067
MCC_NOTIFY_IMPORT_FINISHED_SILENT = 34067
MCC_NOTIFY_ROTATED_IMAGES = 34068
MCC_NOTIFY_LOGIN_STATE_CHANGE = 34069
MCC_NOTIFY_LOGIN_STATE_CHANGE_LOGGED_IN = 34069
MCC_NOTIFY_MYGAL_PROGRESS = 34070
MCC_NOTIFY_MYGAL_DONE = 34071
MCC_NOTIFY_PODCAST_CHANGED = 34072
MCC_NOTIFY_PODCAST_SETTINGS_CHANGED = 34073
MCC_NOTIFY_CONVERT_PROGRESS = 34074
MCC_NOTIFY_CONVERT_UPDATE = 34075
MCC_NOTIFY_BREADCRUMBS_CHANGED = 34076
MCC_NOTIFY_INSTALLED_PLUGINS_CHANGED = 34078
MCC_NOTIFY_SUGGESTED_MUSIC_CHANGED = 34079
MCC_NOTIFY_VIEW_SETTINGS_CHANGED = 34080
MCC_NOTIFY_BEFORE_CONFIGURE_VIEW_SETTINGS = 34081
MCC_NOTIFY_TV_RECORDING_CHANGED = 34082
MCC_NOTIFY_TV_PROGRAMMING_GUIDE_CHANGED = 34083
MCC_NOTIFY_TV_CHANNELS_CHANGED = 34084
MCC_NOTIFY_TV_RECORDING_STARTED = 34085
MCC_NOTIFY_TV_RECORDING_FINISHED = 34086
MCC_NOTIFY_IMPORT_FILES_ADDED = 34087
MCC_NOTIFY_PLAYBACK_OPTIONS_CHANGED = 34088
MCC_NOTIFY_BEFORE_LAYOUT_USER_INTERFACE = 34089
MCC_NOTIFY_AFTER_LAYOUT_USER_INTERFACE = 34090
MCC_NOTIFY_ZONE_ADDED_OR_REMOVED = 34091
MCC_NOTIFY_ZONE_LINKED_OR_UNLINKED = 34092
MCC_NOTIFY_LIBRARY_LOCATIONS_CHANGED = 34093
MCC_NOTIFY_DSP_SETTINGS_CHANGED_IN_CODE = 34094
MCC_NOTIFY_OPTICAL_DISC_CHANGED = 34095
MCC_NOTIFY_STORE_DOWNLOAD_STATUS_CHANGED = 34096
MCC_NOTIFY_CURRENT_PLAYLIST_NEXT_ITEM_TO_PLAY_CHANGED = 34097
MCC_STORE_DOWNLOAD = 35000
MCC_STORE_DOWNLOAD_ALLOW_PURCHASE = 35000
MCC_STORE_PURCHASE = 35001
MCC_STORE_SEARCH_AMAZON = 35002
MCC_STORE_SEARCH_AMAZON_MP3_STORE = 35003
MCC_STORE_TSHIRT = 35004
MCC_STORE_CHANGE_USER = 35005
MCC_STORE_CHECK_FOR_DOWNLOADS = 35006
MCC_UNHANDLED = 0
MCC_UPDATEUI_ENABLE = 1
MCC_UPDATEUI_DISABLE = 2
MCC_UPDATEUI_PRESSED = 4
MCC_UPDATE_FLAG_THUMBNAILS = 1 << 0
MCC_UPDATE_FLAG_FILE_PROPERTIES = 1 << 1
MCC_UPDATE_FLAG_FILE_ADDED_OR_REMOVED = 1 << 2
MCC_UPDATE_FLAG_TREE_STRUCTURE = 1 << 3
MCC_UPDATE_FLAG_REFILL_LIST = 1 << 4
MCC_UPDATE_FLAG_ITEM_DELETED = 1 << 5
MCC_UPDATE_FLAG_NO_PRESERVE_VIEW_STATE = 1 << 6
MCC_UPDATE_FLAG_WEB_VIEW = 1 << 7
MCC_UPDATE_FLAG_ALL = 0x7FFFFFFF & ~MCC_UPDATE_FLAG_NO_PRESERVE_VIEW_STATE
MCC_SETTING_CHANGED_FLAG_UNKNOWN = 1 << 0
MCC_SETTING_CHANGED_FLAG_COLUMNS = 1 << 1
MCC_SETTING_CHANGED_FLAG_SORTING = 1 << 2
MCC_SETTING_CHANGED_FLAG_VIEW_SCHEME = 1 << 3
MCC_SETTING_CHANGED_FLAG_GROUPING = 1 << 5
MCC_SETTING_CHANGED_FLAG_LIBRARY_VIEW_SETTINGS = 1 << 6
MCC_UI_CHANGED_FLAG_FONT = 1 << 0
MCC_UI_CHANGED_FLAG_SKIN = 1 << 1
MCC_UI_CHANGED_FLAG_SCALE = 1 << 2
MCC_UI_CHANGED_FLAG_LANGUAGE = 1 << 3
MCC_UI_CHANGED_FLAG_USER_CHANGE_SKIN = 1 << 4
UI_MODE_UNKNOWN = -2000
UI_MODE_INTERNAL_NO_UI = -1000
UI_MODE_INTERNAL_STANDARD = 0
UI_MODE_INTERNAL_MINI_FREEFORM = 1
UI_MODE_INTERNAL_MINI_SLIM = 2
UI_MODE_INTERNAL_DISPLAY_WINDOWED = 3
UI_MODE_INTERNAL_DISPLAY_FULLSCREEN = 4
UI_MODE_INTERNAL_THEATER = 5
UI_MODE_INTERNAL_COVER = 6
UI_MODE_SHORTCUT_TEMPORARY_DISPLAY_WINDOWED = -8
UI_MODE_SHORTCUT_TOGGLE_DISPLAY_AND_LAST_USER_INPUT_MODE = -7
UI_MODE_SHORTCUT_TOGGLE_DISPLAY_EXCLUDE_THEATER_VIEW = -6
UI_MODE_SHORTCUT_TOGGLE_DISPLAY = -5
UI_MODE_SHORTCUT_LAST_SHUTDOWN = -4
UI_MODE_SHORTCUT_CURRENT = -3
UI_MODE_SHORTCUT_CLOSE_DISPLAY = -2
UI_MODE_SHORTCUT_NEXT = -1
UI_MODE_STANDARD = 0
UI_MODE_MINI = 1
UI_MODE_DISPLAY = 2
UI_MODE_THEATER = 3
UI_MODE_COVER = 4
UI_MODE_COUNT = 5
PLAYER_INFO_CHANGE_ALL = 0xFFFF
PLAYER_INFO_CHANGE_PLAYER_STATE = 1 << 0
PLAYER_INFO_CHANGE_VOLUME = 1 << 1
PLAYER_INFO_CHANGE_FILE_INFO = 1 << 2
PLAYER_INFO_CHANGE_PLAYLIST = 1 << 3
PLAYER_INFO_CHANGE_DSP = 1 << 4
PLAYER_INFO_CHANGE_IMAGE = 1 << 5
PLAYER_INFO_CHANGE_PLAYING_FILE = 1 << 6
PLAYER_INFO_CHANGE_OUTPUT_INFO = 1 << 7
PLAYER_STATUS_CODE_BUFFERING = 0
PLAYER_STATUS_CODE_LOCATING = 1
PLAYER_STATUS_CODE_CONNECTING = 2
PLAYER_STATUS_CODE_DOWNLOADING_CODEC = 3
PLAYER_STATUS_CODE_ACQUIRING_LICENSE = 4
PLAYER_STATUS_CODE_INDIVIDUALIZE_STARTING = 5
PLAYER_STATUS_CODE_INDIVIDUALIZE_CONNECTING = 6
PLAYER_STATUS_CODE_INDIVIDUALIZE_REQUESTING = 7
PLAYER_STATUS_CODE_INDIVIDUALIZE_RECEIVING = 8
PLAYER_STATUS_CODE_INDIVIDUALIZE_COMPLETED = 9
SHOW_THEATER_VIEW_MODE_INVALID = -1
SHOW_THEATER_VIEW_MODE_TOGGLE_THEATER_VIEW = 0
SHOW_THEATER_VIEW_MODE_HOME = 1
SHOW_THEATER_VIEW_MODE_PLAYING_NOW = 2
SHOW_THEATER_VIEW_MODE_AUDIO = 3
SHOW_THEATER_VIEW_MODE_IMAGES = 4
SHOW_THEATER_VIEW_MODE_VIDEOS = 5
SHOW_THEATER_VIEW_MODE_PLAYLISTS = 6
SHOW_THEATER_VIEW_MODE_CD_DVD = 7
SHOW_THEATER_VIEW_MODE_TELEVISION = 8
SHOW_THEATER_VIEW_MODE_TELEVISION_GUIDE = 9
SHOW_THEATER_VIEW_MODE_TELEVISION_RECORDINGS = 10
SHOW_THEATER_VIEW_MODE_LAST_VIEWED = 11
GET_SELECTION_EXACT = 0
GET_SELECTION_ALL_ON_NONE = 1
GET_SELECTION_ALL_ON_ONE_OR_NONE = 2
GET_SELECTION_ALL = 3
GET_SELECTION_EXACT_WITH_POSITION = 4
SKIP_TO_UNDEFINED = 0
SKIP_TO_PREVIOUS_ALBUM = 1
SKIP_TO_NEXT_ALBUM = 2
SKIP_TO_PREVIOUS_ARTIST = 3
SKIP_TO_NEXT_ARTIST = 4


COMMANDS = {
    'Play Pause': {
        'code': MCC_PLAY_PAUSE,
        'value': 0,
    },
    'Play': {
        'code': MCC_PLAY,
        'value': 0,
    },
    'Stop': {
        'code': MCC_STOP,
        'value': False,
    },
    'Stop Display Error': {
        'code': MCC_STOP_DISPLAY_ERROR,
        'value': True,
    },
    'Next': {
        'code': MCC_NEXT,
        'value': 1,
    },
    'Next No Chapters': {
        'code': MCC_NEXT_NO_CHAPTERS,
        'value': 2,
    },
    'Previous': {
        'code': MCC_PREVIOUS,
        'value': 2,
    },
    'Shuffle Toggle': {
        'code': MCC_SHUFFLE_TOGGLE,
        'value': 0,
    },
    'Shuffle Jump': {
        'code': MCC_SHUFFLE_JUMP,
        'value': 1,
    },
    'Shuffle No Jump': {
        'code': MCC_SHUFFLE_NO_JUMP,
        'value': 2,
    },
    'Shuffle Set Mode': {
        'code': MCC_SHUFFLE_SET_MODE,
        'value': 5,
    },
    'Continuous Toggle': {
        'code': MCC_CONTINUOUS_TOGGLE,
        'value': 0,
    },
    'Continuous Off': {
        'code': MCC_CONTINUOUS_OFF,
        'value': 1,
    },
    'Continuous Playlist': {
        'code': MCC_CONTINUOUS_PLAYLIST,
        'value': 2,
    },
    'Continuous Song': {
        'code': MCC_CONTINUOUS_SONG,
        'value': 3,
    },
    'Continuous Stop After Each': {
        'code': MCC_CONTINUOUS_STOP_AFTER_EACH,
        'value': 4,
    },
    'Fast Forward': {
        'code': MCC_FAST_FORWARD,
        'value': range(0, 101),
    },
    'Rewind': {
        'code': MCC_REWIND,
        'value': range(0, 101),
    },
    'Stop Conditional': {
        'code': MCC_STOP_CONDITIONAL,
        'value': 0,
    },
    'Set Zone Next': {
        'code': MCC_SET_ZONE_NEXT,
        'value': -1,
    },
    'Set Zone Previous': {
        'code': MCC_SET_ZONE_PREVIOUS,
        'value': -2,
    },
    'Toggle Display': {
        'code': MCC_TOGGLE_DISPLAY,
        'value': False,
    },
    'Toggle Display No Theater View': {
        'code': MCC_TOGGLE_DISPLAY_NO_THEATER_VIEW,
        'value': True,
    },
    'Show Window': {
        'code': MCC_SHOW_WINDOW,
        'value': False,
    },
    'Show Window Now Playing': {
        'code': MCC_SHOW_WINDOW_NOW_PLAYING,
        'value': True,
    },
    'Minimize Window': {
        'code': MCC_MINIMIZE_WINDOW,
        'value': 0,
    },
    'Play Cpl Database Index': {
        'code': MCC_PLAY_CPLDB_INDEX,
        'value': range(0, 101),
    },
    'Show DSP Studio': {
        'code': MCC_SHOW_DSP_STUDIO,
        'value': 0,
    },
    'Volume Mute Toggle': {
        'code': MCC_VOLUME_MUTE_TOGGLE,
        'value': 0,
    },
    'Volume Mute On': {
        'code': MCC_VOLUME_MUTE_ON,
        'value': 1,
    },
    'Volume Mute Off': {
        'code': MCC_VOLUME_MUTE_OFF,
        'value': 2,
    },
    'Volume Up': {
        'code': MCC_VOLUME_UP,
        'value': range(0, 101),
    },
    'Volume Down': {
        'code': MCC_VOLUME_DOWN,
        'value': range(0, 101),
    },
    'Volume Set': {
        'code': MCC_VOLUME_SET,
        'value': range(0, 101),
    },
    'Show Playback Options': {
        'code': MCC_SHOW_PLAYBACK_OPTIONS,
        'value': 0,
    },
    'Set Pause Toggle': {
        'code': MCC_SET_PAUSE_TOGGLE,
        'value': -1,
    },
    'Set Pause On': {
        'code': MCC_SET_PAUSE_ON,
        'value': True,
    },
    'Set Pause Off': {
        'code': MCC_SET_PAUSE_OFF,
        'value': False,
    },
    'Set Currently Playing Rating': {
        'code': MCC_SET_CURRENTLY_PLAYING_RATING,
        'value': range(0, 101),
    },
    'Show Playback Engine Menu': {
        'code': MCC_SHOW_PLAYBACK_ENGINE_MENU,
        'value': 'screen point (loword: x  hiword: y) -- must send directly',
    },
    'Play Next Playlist': {
        'code': MCC_PLAY_NEXT_PLAYLIST,
        'value': 0,
    },
    'Play Previous Playlist': {
        'code': MCC_PLAY_PREVIOUS_PLAYLIST,
        'value': 0,
    },
    'Maximize Window': {
        'code': MCC_MAXIMIZE_WINDOW,
        'value': 0,
    },
    'Restore Window': {
        'code': MCC_RESTORE_WINDOW,
        'value': 0,
    },
    'Set Player Status': {
        'code': MCC_SET_PLAYERSTATUS,
        'value': 'PLAYER_STATUS_CODES Code',
    },
    'Set Alternate Playback Settings Toggle': {
        'code': MCC_SET_ALTERNATE_PLAYBACK_SETTINGS_TOGGLE,
        'value': -1,
    },
    'Set Alternate Playback Settings On': {
        'code': MCC_SET_ALTERNATE_PLAYBACK_SETTINGS_ON,
        'value': True,
    },
    'Set Alternate Playback Settings Off': {
        'code': MCC_SET_ALTERNATE_PLAYBACK_SETTINGS_OFF,
        'value': False,
    },
    'Set Preview Mode Settings': {
        'code': MCC_SET_PREVIEW_MODE_SETTINGS,
        'value': (
            'low 12 bits: int nDurationSeconds'
            '  high 12 bits: int nStartSeconds'
        ),
    },
    'Show Playback Engine Display Plugin Menu': {
        'code': MCC_SHOW_PLAYBACK_ENGINE_DISPLAY_PLUGIN_MENU,
        'value': 'screen point (loword: x  hiword: y) -- must send directly',
    },
    'DVD Menu': {
        'code': MCC_DVD_MENU,
        'value': 0,
    },
    'Seek Forward': {
        'code': MCC_SEEK_FORWARD,
        'value': range(0, 101),
    },
    'Seek Back': {
        'code': MCC_SEEK_BACK,
        'value': range(0, 101),
    },
    'Stop After Current File Toggle': {
        'code': MCC_STOP_AFTER_CURRENT_FILE_TOGGLE,
        'value': -1,
    },
    'Stop After Current File On': {
        'code': MCC_STOP_AFTER_CURRENT_FILE_ON,
        'value': True,
    },
    'Stop After Current File Off': {
        'code': MCC_STOP_AFTER_CURRENT_FILE_OFF,
        'value': False,
    },
    'Detach Display Toggle': {
        'code': MCC_DETACH_DISPLAY_TOGGLE,
        'value': -1,
    },
    'Detach Display On': {
        'code': MCC_DETACH_DISPLAY_ON,
        'value': True,
    },
    'Detach Display Off': {
        'code': MCC_DETACH_DISPLAY_OFF,
        'value': False,
    },
    'Set Mode Zone Specific': {
        'code': MCC_SET_MODE_ZONE_SPECIFIC,
        'value': [
            UI_MODE_STANDARD,
            UI_MODE_MINI,
            UI_MODE_DISPLAY,
            UI_MODE_THEATER,
            UI_MODE_COVER,
            UI_MODE_COUNT
        ],
    },
    'Stop Internal': {
        'code': MCC_STOP_INTERNAL,
        'value': 0,
    },
    'Playing Now Remove Duplicates': {
        'code': MCC_PLAYING_NOW_REMOVE_DUPLICATES,
        'value': 0,
    },
    'Shuffle Remaining': {
        'code': MCC_SHUFFLE_REMAINING,
        'value': 0,
    },
    'Play First File': {
        'code': MCC_PLAY_FIRST_FILE,
        'value': 0,
    },
    'Play Last File': {
        'code': MCC_PLAY_LAST_FILE,
        'value': 0,
    },
    'Play File By String': {
        'code': MCC_PLAY_FILE_BY_STRING,
        'value': 'BSTR bstrFile (deleted by receiver)',
    },
    'Play File Again': {
        'code': MCC_PLAY_FILE_AGAIN,
        'value': 0,
    },
    'Handle Playback Error': {
        'code': MCC_HANDLE_PLAYBACK_ERROR,
        'value': 0,
    },
    'Play Automatic Playlist': {
        'code': MCC_PLAY_AUTOMATIC_PLAYLIST,
        'value': 'BSTR bstrSeed (deleted by receiver)',
    },
    'Seek': {
        'code': MCC_SEEK,
        'value': range(0, 101),
    },
    'Clear Playing Now Zone Specific All': {
        'code': MCC_CLEAR_PLAYING_NOW_ZONE_SPECIFIC_ALL,
        'value': 0,
    },
    'Clear Playing Now Zone Specific Leave Playing': {
        'code': MCC_CLEAR_PLAYING_NOW_ZONE_SPECIFIC_LEAVE_PLAYING,
        'value': 1,
    },
    'Play Radio Last Fm': {
        'code': MCC_PLAY_RADIO_LAST_FM,
        'value': 0,
    },
    'Show On Screen Display': {
        'code': MCC_SHOW_ON_SCREEN_DISPLAY,
        'value': 0,
    },
    'Set Subtitles': {
        'code': MCC_SET_SUBTITLES,
        'value': range(0, 101),
    },
    'Set Subtitles Previous': {
        'code': MCC_SET_SUBTITLES_PREVIOUS,
        'value': -2,
    },
    'Set Subtitles Next': {
        'code': MCC_SET_SUBTITLES_NEXT,
        'value': -1,
    },
    'Set Audio Stream': {
        'code': MCC_SET_AUDIO_STREAM,
        'value': range(0, 101),
    },
    'Set Audio Stream Previous': {
        'code': MCC_SET_AUDIO_STREAM_PREVIOUS,
        'value': -2,
    },
    'Set Audio Stream Next': {
        'code': MCC_SET_AUDIO_STREAM_NEXT,
        'value': -1,
    },
    'Set Video Stream': {
        'code': MCC_SET_VIDEO_STREAM,
        'value': range(0, 101),
    },
    'Set Video Stream Previous': {
        'code': MCC_SET_VIDEO_STREAM_PREVIOUS,
        'value': -2,
    },
    'Set Video Stream Next': {
        'code': MCC_SET_VIDEO_STREAM_NEXT,
        'value': -1,
    },
    'Video Screen Grab Thumbnail': {
        'code': MCC_VIDEO_SCREEN_GRAB_THUMBNAIL,
        'value': 0,
    },
    'Video Screen Grab Save': {
        'code': MCC_VIDEO_SCREEN_GRAB_SAVE,
        'value': 1,
    },
    'Set Volume Mode Application': {
        'code': MCC_SET_VOLUME_MODE_APPLICATION,
        'value': 0,
    },
    'Set Volume Mode Internal': {
        'code': MCC_SET_VOLUME_MODE_INTERNAL,
        'value': 1,
    },
    'Set Volume Mode System': {
        'code': MCC_SET_VOLUME_MODE_SYSTEM,
        'value': 2,
    },
    'Set Volume Mode Disabled': {
        'code': MCC_SET_VOLUME_MODE_DISABLED,
        'value': 3,
    },
    'Restart Playback': {
        'code': MCC_RESTART_PLAYBACK,
        'value': 0,
    },
    'Zone Switch': {
        'code': MCC_ZONE_SWITCH,
        'value': 0,
    },
    'Skip To': {
        'code': MCC_SKIP_TO,
        'value': 'SKIP_TO_MODES Mode',
    },
    'Link Zone': {
        'code': MCC_LINK_ZONE,
        'value': range(0, 101),
    },
    'Unlink Zone': {
        'code': MCC_UNLINK_ZONE,
        'value': 0,
    },
    'Play Radio Media-Net': {
        'code': MCC_PLAY_RADIO_MEDIANET,
        'value': 0,
    },
    'Clear Played Zone Specific': {
        'code': MCC_CLEAR_PLAYED_ZONE_SPECIFIC,
        'value': 0,
    },
    'Open File': {
        'code': MCC_OPEN_FILE,
        'value': 0,
    },
    'Open Url': {
        'code': MCC_OPEN_URL,
        'value': 0,
    },
    'Print List': {
        'code': MCC_PRINT_LIST,
        'value': 0,
    },
    'Export Playlist Active': {
        'code': MCC_EXPORT_PLAYLIST_ACTIVE,
        'value': -1,
    },
    'Export Playlist': {
        'code': MCC_EXPORT_PLAYLIST,
        'value': range(0, 101),
    },
    'Export All Playlist\'s': {
        'code': MCC_EXPORT_ALL_PLAYLISTS,
        'value': False,
    },
    'Export All Playlist\'s Silent': {
        'code': MCC_EXPORT_ALL_PLAYLISTS_SILENT,
        'value': True,
    },
    'Upload Files': {
        'code': MCC_UPLOAD_FILES,
        'value': 0,
    },
    'Email Files': {
        'code': MCC_EMAIL_FILES,
        'value': 0,
    },
    'Exit': {
        'code': MCC_EXIT,
        'value': 0,
    },
    'Exit Close Server': {
        'code': MCC_EXIT_CLOSE_SERVER,
        'value': 1,
    },
    'Exit Allow Server': {
        'code': MCC_EXIT_ALLOW_SERVER,
        'value': 2,
    },
    'Update Library': {
        'code': MCC_UPDATE_LIBRARY,
        'value': 0,
    },
    'Clear Library': {
        'code': MCC_CLEAR_LIBRARY,
        'value': 0,
    },
    'Export Library': {
        'code': MCC_EXPORT_LIBRARY,
        'value': 0,
    },
    'Backup Library': {
        'code': MCC_BACKUP_LIBRARY,
        'value': 0,
    },
    'Backup Library Silent': {
        'code': MCC_BACKUP_LIBRARY_SILENT,
        'value': 1,
    },
    'Restore Library': {
        'code': MCC_RESTORE_LIBRARY,
        'value': 0,
    },
    'Library Manager': {
        'code': MCC_LIBRARY_MANAGER,
        'value': 0,
    },
    'Image AcqUIre': {
        'code': MCC_IMAGE_ACQUIRE,
        'value': 0,
    },
    'Print Images': {
        'code': MCC_PRINT_IMAGES,
        'value': 'MFKEY nKey (-1 for selected files)',
    },
    'Print': {
        'code': MCC_PRINT,
        'value': 0,
    },
    'Import Playlist': {
        'code': MCC_IMPORT_PLAYLIST,
        'value': 0,
    },
    'Load Library': {
        'code': MCC_LOAD_LIBRARY,
        'value': range(0, 101),
    },
    'Sync Library': {
        'code': MCC_SYNC_LIBRARY,
        'value': 0,
    },
    'Email Podcast Feed': {
        'code': MCC_EMAIL_PODCAST_FEED,
        'value': 0,
    },
    'Load Library Read Only': {
        'code': MCC_LOAD_LIBRARY_READ_ONLY,
        'value': range(0, 101),
    },
    'Add Library': {
        'code': MCC_ADD_LIBRARY,
        'value': 0,
    },
    'Export iTunes': {
        'code': MCC_EXPORT_ITUNES,
        'value': 0,
    },
    'Disconnect Library': {
        'code': MCC_DISCONNECT_LIBRARY,
        'value': 0,
    },
    'Sync With Library Server': {
        'code': MCC_SYNC_WITH_LIBRARY_SERVER,
        'value': 0,
    },
    'Stop All Zones': {
        'code': MCC_STOP_ALL_ZONES,
        'value': False,
    },
    'Stop Remote Zones': {
        'code': MCC_STOP_REMOTE_ZONES,
        'value': True,
    },
    'Clone Library': {
        'code': MCC_CLONE_LIBRARY,
        'value': range(0, 101),
    },
    'Open Live': {
        'code': MCC_OPEN_LIVE,
        'value': 0,
    },
    'Copy': {
        'code': MCC_COPY,
        'value': 0,
    },
    'Paste': {
        'code': MCC_PASTE,
        'value': 0,
    },
    'Select All': {
        'code': MCC_SELECT_ALL,
        'value': 0,
    },
    'Select Invert': {
        'code': MCC_SELECT_INVERT,
        'value': 0,
    },
    'Delete': {
        'code': MCC_DELETE,
        'value': False,
    },
    'Delete Aggressive': {
        'code': MCC_DELETE_AGGRESSIVE,
        'value': True,
    },
    'Rename': {
        'code': MCC_RENAME,
        'value': 0,
    },
    'Undo': {
        'code': MCC_UNDO,
        'value': 0,
    },
    'Redo': {
        'code': MCC_REDO,
        'value': 0,
    },
    'Quick Search': {
        'code': MCC_QUICK_SEARCH,
        'value': False,
    },
    'Repeat Search': {
        'code': MCC_REPEAT_SEARCH,
        'value': True,
    },
    'Add Playlist': {
        'code': MCC_ADD_PLAYLIST,
        'value': 'MEDIAFILE_INFO_ARRAY * paryFiles = NULL',
    },
    'Add Smart List': {
        'code': MCC_ADD_SMARTLIST,
        'value': 0,
    },
    'Add Playlist Group': {
        'code': MCC_ADD_PLAYLIST_GROUP,
        'value': 0,
    },
    'Properties': {
        'code': MCC_PROPERTIES,
        'value': (
            'MEDIAFILE_INFO_ARRAY * paryFiles = NULL (-1 toggles)'
            ' (note: never PostMessage(...) a pointer)'
        ),
    },
    'Toggle Tagging Mode': {
        'code': MCC_TOGGLE_TAGGING_MODE,
        'value': 0,
    },
    'Cut': {
        'code': MCC_CUT,
        'value': 0,
    },
    'Deselect All': {
        'code': MCC_DESELECT_ALL,
        'value': 0,
    },
    'Delete All': {
        'code': MCC_DELETE_ALL,
        'value': False,
    },
    'Delete All Aggressive': {
        'code': MCC_DELETE_ALL_AGGRESSIVE,
        'value': True,
    },
    'Add Podcast Feed': {
        'code': MCC_ADD_PODCAST_FEED,
        'value': 0,
    },
    'Edit Podcast Feed': {
        'code': MCC_EDIT_PODCAST_FEED,
        'value': 0,
    },
    'Add Podcast Defaults': {
        'code': MCC_ADD_PODCAST_DEFAULTS,
        'value': 0,
    },
    'Create Stock Smart Lists': {
        'code': MCC_CREATE_STOCK_SMARTLISTS,
        'value': 0,
    },
    'Enable Podcast Download': {
        'code': MCC_ENABLE_PODCAST_DOWNLOAD,
        'value': 0,
    },
    'Disable Podcast Download': {
        'code': MCC_DISABLE_PODCAST_DOWNLOAD,
        'value': 0,
    },
    'Edit Playlist': {
        'code': MCC_EDIT_PLAYLIST,
        'value': 0,
    },
    'Edit Playing Now': {
        'code': MCC_EDIT_PLAYING_NOW,
        'value': range(0, 101),
    },
    'Edit Disc Information': {
        'code': MCC_EDIT_DISC_INFORMATION,
        'value': 0,
    },
    'Edit Smart List': {
        'code': MCC_EDIT_SMARTLIST,
        'value': range(0, 101),
    },
    'Refresh Podcast Feed': {
        'code': MCC_REFRESH_PODCAST_FEED,
        'value': 0,
    },
    'Lookup Movie Information': {
        'code': MCC_LOOKUP_MOVIE_INFORMATION,
        'value': 0,
    },
    'Add Zone': {
        'code': MCC_ADD_ZONE,
        'value': 0,
    },
    'Add Automatic Playlist': {
        'code': MCC_ADD_AUTOMATIC_PLAYLIST,
        'value': 0,
    },
    'Set Write Tags Toggle': {
        'code': MCC_SET_WRITE_TAGS_TOGGLE,
        'value': -1,
    },
    'Set Write Tags On': {
        'code': MCC_SET_WRITE_TAGS_ON,
        'value': True,
    },
    'Set Write Tags Off': {
        'code': MCC_SET_WRITE_TAGS_OFF,
        'value': False,
    },
    'Paste Tags': {
        'code': MCC_PASTE_TAGS,
        'value': 0,
    },
    'Shuffle Selection': {
        'code': MCC_SHUFFLE_SELECTION,
        'value': 0,
    },
    'Toggle Mode': {
        'code': MCC_TOGGLE_MODE,
        'value': [
            UI_MODE_STANDARD,
            UI_MODE_MINI,
            UI_MODE_DISPLAY,
            UI_MODE_THEATER,
            UI_MODE_COVER,
            UI_MODE_COUNT
        ],
    },
    'Toggle Mode Next': {
        'code': MCC_TOGGLE_MODE_NEXT,
        'value': -1,
    },
    'Theater View': {
        'code': MCC_THEATER_VIEW,
        'value': 'SHOW_THEATER_VIEW_MODES Mode',
    },
    'Party Mode': {
        'code': MCC_PARTY_MODE,
        'value': 0,
    },
    'Show Tree Root': {
        'code': MCC_SHOW_TREE_ROOT,
        'value': range(0, 101),
    },
    'Find Media': {
        'code': MCC_FIND_MEDIA,
        'value': (
            'wchar * pstrSearch (note: memory will be deleted by receiver)'
        ),
    },
    'Back': {
        'code': MCC_BACK,
        'value': range(0, 101),
    },
    'Forward': {
        'code': MCC_FORWARD,
        'value': range(0, 101),
    },
    'Refresh': {
        'code': MCC_REFRESH,
        'value': 'int nFlags (1: no web page refresh)',
    },
    'Set List Style': {
        'code': MCC_SET_LIST_STYLE,
        'value': range(0, 101),
    },
    'Set List Style Toggle': {
        'code': MCC_SET_LIST_STYLE_TOGGLE,
        'value': -1,
    },
    'Set Mode': {
        'code': MCC_SET_MODE,
        'value': [
            UI_MODE_STANDARD,
            UI_MODE_MINI,
            UI_MODE_DISPLAY,
            UI_MODE_THEATER,
            UI_MODE_COVER,
            UI_MODE_COUNT
        ],
    },
    'Show Recently Imported': {
        'code': MCC_SHOW_RECENTLYIMPORTED,
        'value': 0,
    },
    'Show Top Hits': {
        'code': MCC_SHOW_TOPHITS,
        'value': 0,
    },
    'Show Recently Played': {
        'code': MCC_SHOW_RECENTLYPLAYED,
        'value': 0,
    },
    'Set Media Mode': {
        'code': MCC_SET_MEDIA_MODE,
        'value': range(0, 101),
    },
    'Set Server Mode On': {
        'code': MCC_SET_SERVER_MODE_ON,
        'value': True,
    },
    'Set Server Mode Off': {
        'code': MCC_SET_SERVER_MODE_OFF,
        'value': False,
    },
    'Set Mode For External Program Starting': {
        'code': MCC_SET_MODE_FOR_EXTERNAL_PROGRAM_STARTING,
        'value': 0,
    },
    'Set Mode For External Program Ending': {
        'code': MCC_SET_MODE_FOR_EXTERNAL_PROGRAM_ENDING,
        'value': 1,
    },
    'Set Mode For Second Instance Launch': {
        'code': MCC_SET_MODE_FOR_SECOND_INSTANCE_LAUNCH,
        'value': [
            UI_MODE_STANDARD,
            UI_MODE_MINI,
            UI_MODE_DISPLAY,
            UI_MODE_THEATER,
            UI_MODE_COVER,
            UI_MODE_COUNT
        ],
    },
    'Home': {
        'code': MCC_HOME,
        'value': 0,
    },
    'Rollup View Header Toggle': {
        'code': MCC_ROLLUP_VIEW_HEADER_TOGGLE,
        'value': -1,
    },
    'Rollup View Header On': {
        'code': MCC_ROLLUP_VIEW_HEADER_ON,
        'value': True,
    },
    'Rollup View Header Off': {
        'code': MCC_ROLLUP_VIEW_HEADER_OFF,
        'value': False,
    },
    'Focus Search Control': {
        'code': MCC_FOCUS_SEARCH_CONTROL,
        'value': 0,
    },
    'Set Active View Key Toggle': {
        'code': MCC_SET_ACTIVE_VIEW_KEY_TOGGLE,
        'value': -1,
    },
    'Set Active View Key Toggle Back': {
        'code': MCC_SET_ACTIVE_VIEW_KEY_TOGGLE_BACK,
        'value': -2,
    },
    'Set Active View Key New': {
        'code': MCC_SET_ACTIVE_VIEW_KEY_NEW,
        'value': -3,
    },
    'Set Active View Key': {
        'code': MCC_SET_ACTIVE_VIEW_KEY,
        'value': range(0, 101),
    },
    'Close View Key': {
        'code': MCC_CLOSE_VIEW_KEY,
        'value': range(0, 101),
    },
    'Close View Key Current': {
        'code': MCC_CLOSE_VIEW_KEY_CURRENT,
        'value': -1,
    },
    'View Zoom Set': {
        'code': MCC_VIEW_ZOOM_SET,
        'value': range(0, 101),
    },
    'View Zoom Increment': {
        'code': MCC_VIEW_ZOOM_INCREMENT,
        'value': range(0, 101),
    },
    'Find Media With Wizard': {
        'code': MCC_FIND_MEDIA_WITH_WIZARD,
        'value': 0,
    },
    'Set User': {
        'code': MCC_SET_USER,
        'value': range(0, 101),
    },
    'Show Tree Toggle': {
        'code': MCC_SHOW_TREE_TOGGLE,
        'value': -1,
    },
    'Show Tree On': {
        'code': MCC_SHOW_TREE_ON,
        'value': True,
    },
    'Show Tree Off': {
        'code': MCC_SHOW_TREE_OFF,
        'value': False,
    },
    'Set Tooltips Toggle': {
        'code': MCC_SET_TOOLTIPS_TOGGLE,
        'value': -1,
    },
    'Set Tooltips On': {
        'code': MCC_SET_TOOLTIPS_ON,
        'value': True,
    },
    'Set Tooltips Off': {
        'code': MCC_SET_TOOLTIPS_OFF,
        'value': False,
    },
    'Audio Only Mode Toggle': {
        'code': MCC_AUDIO_ONLY_MODE_TOGGLE,
        'value': -1,
    },
    'Audio Only Mode On': {
        'code': MCC_AUDIO_ONLY_MODE_ON,
        'value': True,
    },
    'Audio Only Mode Off': {
        'code': MCC_AUDIO_ONLY_MODE_OFF,
        'value': False,
    },
    'Import Disable Running Warning': {
        'code': MCC_IMPORT_DISABLE_RUNNING_WARNING,
        'value': 1,
    },
    'Import First Import Mode': {
        'code': MCC_IMPORT_FIRST_IMPORT_MODE,
        'value': 2,
    },
    'Rip CD': {
        'code': MCC_RIP_CD,
        'value': 0,
    },
    'Burn': {
        'code': MCC_BURN,
        'value': 0,
    },
    'Record Audio': {
        'code': MCC_RECORD_AUDIO,
        'value': 0,
    },
    'Convert': {
        'code': MCC_CONVERT,
        'value': 0,
    },
    'Analyze Audio': {
        'code': MCC_ANALYZE_AUDIO,
        'value': 0,
    },
    'Media Editor': {
        'code': MCC_MEDIA_EDITOR,
        'value': 0,
    },
    'CD Labeler': {
        'code': MCC_CD_LABELER,
        'value': 0,
    },
    'Skin Manager': {
        'code': MCC_SKIN_MANAGER,
        'value': 0,
    },
    'Options': {
        'code': MCC_OPTIONS,
        'value': range(0, 101),
    },
    'Rename CD Files': {
        'code': MCC_RENAME_CD_FILES,
        'value': 0,
    },
    'Handheld Upload': {
        'code': MCC_HANDHELD_UPLOAD,
        'value': (
            'loword: nDeviceSessionID (0 gets default)  '
            'hiword: flags (1: sync only; 2: show warnings)'
        ),
    },
    'Handheld Update Upload Worker Finished': {
        'code': MCC_HANDHELD_UPDATE_UPLOAD_WORKER_FINISHED,
        'value': range(0, 101),
    },
    'Handheld Close Device': {
        'code': MCC_HANDHELD_CLOSE_DEVICE,
        'value': range(0, 101),
    },
    'Handheld Show Options': {
        'code': MCC_HANDHELD_SHOW_OPTIONS,
        'value': range(0, 101),
    },
    'Handheld Info Dump On': {
        'code': MCC_HANDHELD_INFO_DUMP_ON,
        'value': True,
    },
    'Handheld Info Dump Off': {
        'code': MCC_HANDHELD_INFO_DUMP_OFF,
        'value': False,
    },
    'Import Auto Run Now': {
        'code': MCC_IMPORT_AUTO_RUN_NOW,
        'value': False,
    },
    'Import Auto Run Now Silent': {
        'code': MCC_IMPORT_AUTO_RUN_NOW_SILENT,
        'value': True,
    },
    'Import Auto Configure': {
        'code': MCC_IMPORT_AUTO_CONFIGURE,
        'value': 0,
    },
    'Handheld Eject': {
        'code': MCC_HANDHELD_EJECT,
        'value': range(0, 101),
    },
    'Record TV': {
        'code': MCC_RECORD_TV,
        'value': 0,
    },
    'Find And Replace': {
        'code': MCC_FIND_AND_REPLACE,
        'value': 0,
    },
    'Clean Properties': {
        'code': MCC_CLEAN_PROPERTIES,
        'value': 0,
    },
    'Fill Track Order': {
        'code': MCC_FILL_TRACK_ORDER,
        'value': 0,
    },
    'Move Copy Fields': {
        'code': MCC_MOVE_COPY_FIELDS,
        'value': 0,
    },
    'Remove Tags': {
        'code': MCC_REMOVE_TAGS,
        'value': 0,
    },
    'Update Tags From Database': {
        'code': MCC_UPDATE_TAGS_FROM_DB,
        'value': 0,
    },
    'Update Db From Tags': {
        'code': MCC_UPDATE_DB_FROM_TAGS,
        'value': 0,
    },
    'Lookup Track Info From Internet': {
        'code': MCC_LOOKUP_TRACK_INFO_FROM_INTERNET,
        'value': 0,
    },
    'Submit Track Info To Internet': {
        'code': MCC_SUBMIT_TRACK_INFO_TO_INTERNET,
        'value': 0,
    },
    'Fill Properties From Filename': {
        'code': MCC_FILL_PROPERTIES_FROM_FILENAME,
        'value': 0,
    },
    'Rename Files From Properties': {
        'code': MCC_RENAME_FILES_FROM_PROPERTIES,
        'value': 0,
    },
    'Cover Art Add From File': {
        'code': MCC_COVER_ART_ADD_FROM_FILE,
        'value': 0,
    },
    'Cover Art Quick Add From File': {
        'code': MCC_COVER_ART_QUICK_ADD_FROM_FILE,
        'value': 0,
    },
    'Cover Art Get From Internet': {
        'code': MCC_COVER_ART_GET_FROM_INTERNET,
        'value': 0,
    },
    'Cover Art Submit To Internet': {
        'code': MCC_COVER_ART_SUBMIT_TO_INTERNET,
        'value': 0,
    },
    'Cover Art Get From Scanner': {
        'code': MCC_COVER_ART_GET_FROM_SCANNER,
        'value': 0,
    },
    'Cover Art Select Scanner': {
        'code': MCC_COVER_ART_SELECT_SCANNER,
        'value': 0,
    },
    'Cover Art Get From Clipboard': {
        'code': MCC_COVER_ART_GET_FROM_CLIPBOARD,
        'value': 0,
    },
    'Cover Art Copy To Clipboard': {
        'code': MCC_COVER_ART_COPY_TO_CLIPBOARD,
        'value': 0,
    },
    'Cover Art Remove': {
        'code': MCC_COVER_ART_REMOVE,
        'value': 0,
    },
    'Cover Art Play': {
        'code': MCC_COVER_ART_PLAY,
        'value': 0,
    },
    'Cover Art Save To External File': {
        'code': MCC_COVER_ART_SAVE_TO_EXTERNAL_FILE,
        'value': 0,
    },
    'Cover Art Rebuild Thumbnail': {
        'code': MCC_COVER_ART_REBUILD_THUMBNAIL,
        'value': 0,
    },
    'Ring Tone': {
        'code': MCC_RINGTONE,
        'value': 0,
    },
    'Audio Calibration': {
        'code': MCC_AUDIO_CALIBRATION,
        'value': 0,
    },
    'Mark Played': {
        'code': MCC_MARK_PLAYED,
        'value': 0,
    },
    'Mark Not Played': {
        'code': MCC_MARK_NOT_PLAYED,
        'value': 0,
    },
    'Link Tracks': {
        'code': MCC_LINK_TRACKS,
        'value': 0,
    },
    'Break Track Links': {
        'code': MCC_BREAK_TRACK_LINKS,
        'value': 0,
    },
    'Help Contents': {
        'code': MCC_HELP_CONTENTS,
        'value': 0,
    },
    'Help How-to Import Files': {
        'code': MCC_HELP_HOWTO_IMPORT_FILES,
        'value': 0,
    },
    'Help How-to Play Files': {
        'code': MCC_HELP_HOWTO_PLAY_FILES,
        'value': 0,
    },
    'Help How-to Rip': {
        'code': MCC_HELP_HOWTO_RIP,
        'value': 0,
    },
    'Help How-to Burn': {
        'code': MCC_HELP_HOWTO_BURN,
        'value': 0,
    },
    'Help How-to Organize Files': {
        'code': MCC_HELP_HOWTO_ORGANIZE_FILES,
        'value': 0,
    },
    'Help How-to View Schemes': {
        'code': MCC_HELP_HOWTO_VIEW_SCHEMES,
        'value': 0,
    },
    'Help How-to Manage Playlist': {
        'code': MCC_HELP_HOWTO_MANAGE_PLAYLISTS,
        'value': 0,
    },
    'Help How-to Edit Properties': {
        'code': MCC_HELP_HOWTO_EDIT_PROPERTIES,
        'value': 0,
    },
    'Help How-to Find': {
        'code': MCC_HELP_HOWTO_FIND,
        'value': 0,
    },
    'Help How-to Configure': {
        'code': MCC_HELP_HOWTO_CONFIGURE,
        'value': 0,
    },
    'Check For Updates': {
        'code': MCC_CHECK_FOR_UPDATES,
        'value': 0,
    },
    'Buy': {
        'code': MCC_BUY,
        'value': 0,
    },
    'Install License': {
        'code': MCC_INSTALL_LICENSE,
        'value': 0,
    },
    'Registration Info': {
        'code': MCC_REGISTRATION_INFO,
        'value': 0,
    },
    'Plus Features': {
        'code': MCC_PLUS_FEATURES,
        'value': 0,
    },
    'Interact': {
        'code': MCC_INTERACT,
        'value': 0,
    },
    'System Info': {
        'code': MCC_SYSTEM_INFO,
        'value': 0,
    },
    'About': {
        'code': MCC_ABOUT,
        'value': 0,
    },
    'Configure Debug Logging': {
        'code': MCC_CONFIGURE_DEBUG_LOGGING,
        'value': 0,
    },
    'Wiki': {
        'code': MCC_WIKI,
        'value': 0,
    },
    'Test': {
        'code': MCC_TEST,
        'value': 0,
    },
    'Show Eula': {
        'code': MCC_SHOW_EULA,
        'value': 0,
    },
    'Benchmark': {
        'code': MCC_BENCHMARK,
        'value': 0,
    },
    'Upgrade To Master License': {
        'code': MCC_UPGRADE_TO_MASTER_LICENSE,
        'value': 0,
    },
    'Add View Scheme': {
        'code': MCC_ADD_VIEW_SCHEME,
        'value': 0,
    },
    'Edit View Scheme': {
        'code': MCC_EDIT_VIEW_SCHEME,
        'value': 0,
    },
    'Tree Add Directory': {
        'code': MCC_TREE_ADD_DIRECTORY,
        'value': 0,
    },
    'Tree Import': {
        'code': MCC_TREE_IMPORT,
        'value': 0,
    },
    'Tree Add CD Folder': {
        'code': MCC_TREE_ADD_CD_FOLDER,
        'value': 0,
    },
    'Update From CD Database': {
        'code': MCC_UPDATE_FROM_CD_DATABASE,
        'value': 0,
    },
    'Submit To CD Database': {
        'code': MCC_SUBMIT_TO_CD_DATABASE,
        'value': 0,
    },
    'Tree Rip': {
        'code': MCC_TREE_RIP,
        'value': 0,
    },
    'Clear Playing Now': {
        'code': MCC_CLEAR_PLAYING_NOW,
        'value': 0,
    },
    'Clear Playing Now Leave Playing': {
        'code': MCC_CLEAR_PLAYING_NOW_LEAVE_PLAYING,
        'value': 1,
    },
    'Copy Listening To': {
        'code': MCC_COPY_LISTENING_TO,
        'value': False,
    },
    'Copy Listening To Paste': {
        'code': MCC_COPY_LISTENING_TO_PASTE,
        'value': True,
    },
    'Tree Set Expanded': {
        'code': MCC_TREE_SET_EXPANDED,
        'value': 1,
    },
    'Tree Set Collapsed': {
        'code': MCC_TREE_SET_COLLAPSED,
        'value': 0,
    },
    'Reset View Schemes': {
        'code': MCC_RESET_VIEW_SCHEMES,
        'value': 0,
    },
    'Tree Erase CD DVD': {
        'code': MCC_TREE_ERASE_CD_DVD,
        'value': 0,
    },
    'Update From CD Player INI': {
        'code': MCC_UPDATE_FROM_CDPLAYER_INI,
        'value': 0,
    },
    'Tree Eject': {
        'code': MCC_TREE_EJECT,
        'value': 0,
    },
    'Tree Add Virtual Device': {
        'code': MCC_TREE_ADD_VIRTUAL_DEVICE,
        'value': 0,
    },
    'Tree Rename Playlist': {
        'code': MCC_TREE_RENAME_PLAYLIST,
        'value': range(0, 101),
    },
    'Twitter Listening To': {
        'code': MCC_TWITTER_LISTENING_TO,
        'value': 0,
    },
    'Scrobble Listening To': {
        'code': MCC_SCROBBLE_LISTENING_TO,
        'value': 0,
    },
    'List Update Order': {
        'code': MCC_LIST_UPDATE_ORDER,
        'value': 0,
    },
    'List Shuffle Order': {
        'code': MCC_LIST_SHUFFLE_ORDER,
        'value': 0,
    },
    'List Import': {
        'code': MCC_LIST_IMPORT,
        'value': 0,
    },
    'List Remove Order': {
        'code': MCC_LIST_REMOVE_ORDER,
        'value': 0,
    },
    'Locate File Disk Internal': {
        'code': MCC_LOCATE_FILE_DISK_INTERNAL,
        'value': -1,
    },
    'Locate File Disk External': {
        'code': MCC_LOCATE_FILE_DISK_EXTERNAL,
        'value': -2,
    },
    'Locate File': {
        'code': MCC_LOCATE_FILE,
        'value': range(0, 101),
    },
    'List Increment Selection': {
        'code': MCC_LIST_INCREMENT_SELECTION,
        'value': range(0, 101),
    },
    'List Remove Duplicates': {
        'code': MCC_LIST_REMOVE_DUPLICATES,
        'value': 0,
    },
    'List Auto Size Column': {
        'code': MCC_LIST_AUTO_SIZE_COLUMN,
        'value': range(0, 101),
    },
    'List Auto Size Column All': {
        'code': MCC_LIST_AUTO_SIZE_COLUMN_ALL,
        'value': -1,
    },
    'List Customize View': {
        'code': MCC_LIST_CUSTOMIZE_VIEW,
        'value': 0,
    },
    'List Copy Disk Files': {
        'code': MCC_LIST_COPY_DISK_FILES,
        'value': 0,
    },
    'List Set Rip Check Toggle': {
        'code': MCC_LIST_SET_RIP_CHECK_TOGGLE,
        'value': -1,
    },
    'List Set Rip Check On': {
        'code': MCC_LIST_SET_RIP_CHECK_ON,
        'value': 1,
    },
    'List Set Rip Check Off': {
        'code': MCC_LIST_SET_RIP_CHECK_OFF,
        'value': 0,
    },
    'List Download': {
        'code': MCC_LIST_DOWNLOAD,
        'value': 0,
    },
    'List Get List Pointer': {
        'code': MCC_LIST_GET_LIST_POINTER,
        'value': 0,
    },
    'Locate Stack': {
        'code': MCC_LOCATE_STACK,
        'value': 0,
    },
    'Set As Stack Top': {
        'code': MCC_SET_AS_STACK_TOP,
        'value': 0,
    },
    'Expand Stack': {
        'code': MCC_EXPAND_STACK,
        'value': 0,
    },
    'Collapse Stack': {
        'code': MCC_COLLAPSE_STACK,
        'value': 0,
    },
    'Auto Stack Name': {
        'code': MCC_AUTOSTACK_NAME,
        'value': 0,
    },
    'Auto Stack Artist Album Name': {
        'code': MCC_AUTOSTACK_ARTIST_ALBUM_NAME,
        'value': 1,
    },
    'Auto Stack Artist Album Track': {
        'code': MCC_AUTOSTACK_ARTIST_ALBUM_TRACK,
        'value': 2,
    },
    'Check Stacks': {
        'code': MCC_CHECK_STACKS,
        'value': 0,
    },
    'Stack': {
        'code': MCC_STACK,
        'value': range(0, 101),
    },
    'Unstack': {
        'code': MCC_UNSTACK,
        'value': 0,
    },
    'Add To Stack': {
        'code': MCC_ADD_TO_STACK,
        'value': 0,
    },
    'Pane Reset Selection': {
        'code': MCC_PANE_RESET_SELECTION,
        'value': range(0, 101),
    },
    'Pane Reset Selection All': {
        'code': MCC_PANE_RESET_SELECTION_ALL,
        'value': -1,
    },
    'List Remove All': {
        'code': MCC_LIST_REMOVE_ALL,
        'value': 0,
    },
    'List Lock Toggle': {
        'code': MCC_LIST_LOCK_TOGGLE,
        'value': -1,
    },
    'List Lock On': {
        'code': MCC_LIST_LOCK_ON,
        'value': True,
    },
    'List Lock Off': {
        'code': MCC_LIST_LOCK_OFF,
        'value': False,
    },
    'Pane Set Expanded': {
        'code': MCC_PANE_SET_EXPANDED,
        'value': 'loword: nPaneIndex  hiword: 0: collapsed; 1: expanded',
    },
    'Keystroke': {
        'code': MCC_KEYSTROKE,
        'value': range(0, 101),
    },
    'PC Shutdown': {
        'code': MCC_PC_SHUTDOWN,
        'value': 0,
    },
    'PC Hibernate': {
        'code': MCC_PC_HIBERNATE,
        'value': 2,
    },
    'PC Sleep': {
        'code': MCC_PC_SLEEP,
        'value': 1,
    },
    'PC Restart': {
        'code': MCC_PC_RESTART,
        'value': 3,
    },
    'Playback Engine Zoom In': {
        'code': MCC_PLAYBACK_ENGINE_ZOOM_IN,
        'value': 0,
    },
    'Playback Engine Zoom Out': {
        'code': MCC_PLAYBACK_ENGINE_ZOOM_OUT,
        'value': 0,
    },
    'Playback Engine Up': {
        'code': MCC_PLAYBACK_ENGINE_UP,
        'value': 0,
    },
    'Playback Engine Down': {
        'code': MCC_PLAYBACK_ENGINE_DOWN,
        'value': 0,
    },
    'Playback Engine Left': {
        'code': MCC_PLAYBACK_ENGINE_LEFT,
        'value': 0,
    },
    'Playback Engine Right': {
        'code': MCC_PLAYBACK_ENGINE_RIGHT,
        'value': 0,
    },
    'Playback Engine Enter': {
        'code': MCC_PLAYBACK_ENGINE_ENTER,
        'value': 0,
    },
    'Playback Engine First': {
        'code': MCC_PLAYBACK_ENGINE_FIRST,
        'value': 0,
    },
    'Playback Engine Last': {
        'code': MCC_PLAYBACK_ENGINE_LAST,
        'value': 0,
    },
    'Playback Engine Next': {
        'code': MCC_PLAYBACK_ENGINE_NEXT,
        'value': 0,
    },
    'Playback Engine Previous': {
        'code': MCC_PLAYBACK_ENGINE_PREVIOUS,
        'value': 0,
    },
    'Playback Engine Pause Toggle': {
        'code': MCC_PLAYBACK_ENGINE_PAUSE_TOGGLE,
        'value': -1,
    },
    'Playback Engine Pause On': {
        'code': MCC_PLAYBACK_ENGINE_PAUSE_ON,
        'value': True,
    },
    'Playback Engine Pause Off': {
        'code': MCC_PLAYBACK_ENGINE_PAUSE_OFF,
        'value': False,
    },
    'Image Pan And Zoom Toggle': {
        'code': MCC_IMAGE_PAN_AND_ZOOM_TOGGLE,
        'value': -1,
    },
    'Image Pan And Zoom On': {
        'code': MCC_IMAGE_PAN_AND_ZOOM_ON,
        'value': True,
    },
    'Image Pan And Zoom Off': {
        'code': MCC_IMAGE_PAN_AND_ZOOM_OFF,
        'value': False,
    },
    'Image Toggle Effect': {
        'code': MCC_IMAGE_TOGGLE_EFFECT,
        'value': range(0, 101),
    },
    'Image Rapid Zoom': {
        'code': MCC_IMAGE_RAPID_ZOOM,
        'value': range(0, 101),
    },
    'DVD Set Audio Stream Toggle': {
        'code': MCC_DVD_SET_AUDIO_STREAM_TOGGLE,
        'value': -1,
    },
    'DVD Set Audio Stream': {
        'code': MCC_DVD_SET_AUDIO_STREAM,
        'value': range(0, 101),
    },
    'DVD Show Menu': {
        'code': MCC_DVD_SHOW_MENU,
        'value': 0,
    },
    'TV Record': {
        'code': MCC_TV_RECORD,
        'value': 0,
    },
    'TV Snapshot': {
        'code': MCC_TV_SNAPSHOT,
        'value': 0,
    },
    'TV Change Standard': {
        'code': MCC_TV_CHANGE_STANDARD,
        'value': 0,
    },
    'Playback Engine OSD Video Process Amp': {
        'code': MCC_PLAYBACK_ENGINE_OSD_VIDEO_PROC_AMP,
        'value': (
            'int nIndex (0 for brightness  1 for contrast  etc. -1 cycles)'
        ),
    },
    'Playback Engine Set Current Video Process Amp': {
        'code': MCC_PLAYBACK_ENGINE_SET_CUR_VIDEO_PROC_AMP,
        'value': (
            'int nStep (... -2  -1  1  2  etc.'
            ' 0 is invalid and will default to 1)'
        ),
    },
    'Playback Engine Set Aspect Ratio Toggle': {
        'code': MCC_PLAYBACK_ENGINE_SET_ASPECT_RATIO_TOGGLE,
        'value': -1,
    },
    'Playback Engine Set Aspect Ratio': {
        'code': MCC_PLAYBACK_ENGINE_SET_ASPECT_RATIO,
        'value': range(0, 101),
    },
    'Playback Engine Scroll Up': {
        'code': MCC_PLAYBACK_ENGINE_SCROLL_UP,
        'value': 0,
    },
    'Playback Engine Scroll Down': {
        'code': MCC_PLAYBACK_ENGINE_SCROLL_DOWN,
        'value': 0,
    },
    'Playback Engine Scroll Left': {
        'code': MCC_PLAYBACK_ENGINE_SCROLL_LEFT,
        'value': 0,
    },
    'Playback Engine Scroll Right': {
        'code': MCC_PLAYBACK_ENGINE_SCROLL_RIGHT,
        'value': 0,
    },
    'TV Set Save Time Shifting Increase': {
        'code': MCC_TV_SET_SAVE_TIME_SHIFTING_INCREASE,
        'value': -1,
    },
    'TV Set Save Time Shifting Decrease': {
        'code': MCC_TV_SET_SAVE_TIME_SHIFTING_DECREASE,
        'value': -2,
    },
    'TV Set Save Time Shifting': {
        'code': MCC_TV_SET_SAVE_TIME_SHIFTING,
        'value': range(0, 101),
    },
    'Playback Engine Zoom To Preset Fit': {
        'code': MCC_PLAYBACK_ENGINE_ZOOM_TO_PRESET_FIT,
        'value': 0,
    },
    'Playback Engine Zoom To Preset 100': {
        'code': MCC_PLAYBACK_ENGINE_ZOOM_TO_PRESET_100,
        'value': 1,
    },
    'Playback Engine Zoom To Preset 200': {
        'code': MCC_PLAYBACK_ENGINE_ZOOM_TO_PRESET_200,
        'value': 2,
    },
    'TV Scan Programming Events': {
        'code': MCC_TV_SCAN_PROGRAMMING_EVENTS,
        'value': 0,
    },
    'TV Change Channel Key': {
        'code': MCC_TV_CHANGE_CHANNEL_KEY,
        'value': range(0, 101),
    },
    'TV Play Channel Position': {
        'code': MCC_TV_PLAY_CHANNEL_POSITION,
        'value': range(0, 101),
    },
    'Playback Engine Set Subtitles Next': {
        'code': MCC_PLAYBACK_ENGINE_SET_SUBTITLES_NEXT,
        'value': -1,
    },
    'Playback Engine Set Subtitles Previous': {
        'code': MCC_PLAYBACK_ENGINE_SET_SUBTITLES_PREVIOUS,
        'value': -2,
    },
    'Playback Engine Set Subtitles': {
        'code': MCC_PLAYBACK_ENGINE_SET_SUBTITLES,
        'value': range(0, 101),
    },
    'Playback Engine Set Audio Stream Next': {
        'code': MCC_PLAYBACK_ENGINE_SET_AUDIO_STREAM_NEXT,
        'value': -1,
    },
    'Playback Engine Set Audio Stream Previous': {
        'code': MCC_PLAYBACK_ENGINE_SET_AUDIO_STREAM_PREVIOUS,
        'value': -2,
    },
    'Playback Engine Set Audio Stream': {
        'code': MCC_PLAYBACK_ENGINE_SET_AUDIO_STREAM,
        'value': range(0, 101),
    },
    'Playback Engine Set Video Stream Next': {
        'code': MCC_PLAYBACK_ENGINE_SET_VIDEO_STREAM_NEXT,
        'value': -1,
    },
    'Playback Engine Set Video Stream Previous': {
        'code': MCC_PLAYBACK_ENGINE_SET_VIDEO_STREAM_PREVIOUS,
        'value': -2,
    },
    'Playback Engine Set Video Stream': {
        'code': MCC_PLAYBACK_ENGINE_SET_VIDEO_STREAM,
        'value': range(0, 101),
    },
    'Playback Engine Video Screen Grab Thumbnail': {
        'code': MCC_PLAYBACK_ENGINE_VIDEO_SCREEN_GRAB_THUMBNAIL,
        'value': 0,
    },
    'Playback Engine Video Screen Grab Save': {
        'code': MCC_PLAYBACK_ENGINE_VIDEO_SCREEN_GRAB_SAVE,
        'value': 1,
    },
    'Playback Engine Video Lip-sync': {
        'code': MCC_PLAYBACK_ENGINE_VIDEO_LIPSYNC,
        'value': range(0, 101),
    },
    'Playback Engine Set Subtitle Timing': {
        'code': MCC_PLAYBACK_ENGINE_SET_SUBTITLE_TIMING,
        'value': range(0, 101),
    },
    'Reload MC View': {
        'code': MCC_RELOAD_MC_VIEW,
        'value': 0,
    },
    'Customize Toolbar': {
        'code': MCC_CUSTOMIZE_TOOLBAR,
        'value': 0,
    },
    'Play TV': {
        'code': MCC_PLAY_TV,
        'value': range(0, 101),
    },
    'Update Web Pages': {
        'code': MCC_UPDATE_WEBPAGES,
        'value': 0,
    },
    'Show Running Mc On': {
        'code': MCC_SHOW_RUNNING_MC_ON,
        'value': True,
    },
    'Show Running Mc Off': {
        'code': MCC_SHOW_RUNNING_MC_OFF,
        'value': False,
    },
    'Show Menu': {
        'code': MCC_SHOW_MENU,
        'value': range(0, 101),
    },
    'Tune TV': {
        'code': MCC_TUNE_TV,
        'value': 0,
    },
    'Play Playlist': {
        'code': MCC_PLAY_PLAYLIST,
        'value': range(0, 101),
    },
    'Sendto Tool Labeler': {
        'code': MCC_SENDTO_TOOL_LABELER,
        'value': 0,
    },
    'Sendto Tool Media Editor': {
        'code': MCC_SENDTO_TOOL_MEDIA_EDITOR,
        'value': 1,
    },
    'Sendto Tool Default Editor': {
        'code': MCC_SENDTO_TOOL_DEFAULT_EDITOR,
        'value': 2,
    },
    'Sendto Tool Ftp': {
        'code': MCC_SENDTO_TOOL_FTP,
        'value': 3,
    },
    'Sendto Tool Email': {
        'code': MCC_SENDTO_TOOL_EMAIL,
        'value': 4,
    },
    'Sendto Tool Menalto Gallery': {
        'code': MCC_SENDTO_TOOL_MENALTO_GALLERY,
        'value': 5,
    },
    'Sendto Tool Web Gallery': {
        'code': MCC_SENDTO_TOOL_WEB_GALLERY,
        'value': 6,
    },
    'Configure Theater View': {
        'code': MCC_CONFIGURE_THEATER_VIEW,
        'value': 0,
    },
    'Set Status Text': {
        'code': MCC_SET_STATUSTEXT,
        'value': 'BSTR bstrText (deleted by receiver)',
    },
    'Update UI After Active Window Change': {
        'code': MCC_UPDATE_UI_AFTER_ACTIVE_WINDOW_CHANGE,
        'value': 0,
    },
    'Re-enum Portable Devices': {
        'code': MCC_REENUM_PORTABLE_DEVICES,
        'value': False,
    },
    'Re-enum Portable Devices Connected': {
        'code': MCC_REENUM_PORTABLE_DEVICES_CONNECTED,
        'value': True,
    },
    'Play Advanced': {
        'code': MCC_PLAY_ADVANCED,
        'value': 'PLAY_COMMAND * pCommand (deleted by receiver)',
    },
    'Update Status Bar': {
        'code': MCC_UPDATE_STATUS_BAR,
        'value': 0,
    },
    'Request Podcast Update': {
        'code': MCC_REQUEST_PODCAST_UPDATE,
        'value': 0,
    },
    'Request Podcast Purge': {
        'code': MCC_REQUEST_PODCAST_PURGE,
        'value': 0,
    },
    'Show Invalid CD Volume Warning': {
        'code': MCC_SHOW_INVALID_CD_VOLUME_WARNING,
        'value': list('ABCDEFGHIJKLMNOTQRSTUVWXYZ'),
    },
    'Play TV Channel For Client': {
        'code': MCC_PLAY_TV_CHANNEL_FOR_CLIENT,
        'value': 'the MFKEY key of the TV channel to be played',
    },
    'Stop Serving TV File': {
        'code': MCC_STOP_SERVING_TV_FILE,
        'value': 'CTVPlayer *: pointer to TVPlayer object serving the file',
    },
    'Show Device Presentation Web Page': {
        'code': MCC_SHOW_DEVICE_PRESENTATION_WEBPAGE,
        'value': range(0, 101),
    },
    'Image Set Desktop Back': {
        'code': MCC_IMAGE_SET_DESKTOP_BACK,
        'value': 0,
    },
    'Image Rotate Left': {
        'code': MCC_IMAGE_ROTATE_LEFT,
        'value': 0,
    },
    'Image Rotate Right': {
        'code': MCC_IMAGE_ROTATE_RIGHT,
        'value': 0,
    },
    'Image Rotate Upside Down': {
        'code': MCC_IMAGE_ROTATE_UPSIDEDOWN,
        'value': 0,
    },
    'Image Resize': {
        'code': MCC_IMAGE_RESIZE,
        'value': 0,
    },
    'Image Edit': {
        'code': MCC_IMAGE_EDIT,
        'value': range(0, 101),
    },
    'Image Delete': {
        'code': MCC_IMAGE_DELETE,
        'value': range(0, 101),
    },
    'Image Preview Show': {
        'code': MCC_IMAGE_PREVIEW_SHOW,
        'value': 0,
    },
    'Image Preview Hide': {
        'code': MCC_IMAGE_PREVIEW_HIDE,
        'value': 0,
    },
    'Image Locate On Map': {
        'code': MCC_IMAGE_LOCATE_ON_MAP,
        'value': 0,
    },
    'Get Selected Files': {
        'code': MCC_GET_SELECTED_FILES,
        'value': (
            'loword: GET_SELECTION_MODES Mode  hiword: short nFlags '
            '(1: for playback  2: disable when in a grouping view)'
        ),
    },
    'Print View': {
        'code': MCC_PRINTVIEW,
        'value': 0,
    },
    'Output': {
        'code': MCC_OUTPUT,
        'value': range(0, 101),
    },
    'Output Active View': {
        'code': MCC_OUTPUT_ACTIVE_VIEW,
        'value': -1,
    },
    'Set Focus': {
        'code': MCC_SETFOCUS,
        'value': 0,
    },
    'Select Files': {
        'code': MCC_SELECT_FILES,
        'value': 'CMediaArray *',
    },
    'Double Click': {
        'code': MCC_DOUBLE_CLICK,
        'value': 0,
    },
    'Play Or Show': {
        'code': MCC_PLAY_OR_SHOW,
        'value': 0,
    },
    'Show Current File Force': {
        'code': MCC_SHOW_CURRENT_FILE_FORCE,
        'value': 1,
    },
    'Show Current File Select': {
        'code': MCC_SHOW_CURRENT_FILE_SELECT,
        'value': 2,
    },
    'Buy Selected Tracks': {
        'code': MCC_BUY_SELECTED_TRACKS,
        'value': range(0, 101),
    },
    'Buy All Tracks': {
        'code': MCC_BUY_ALL_TRACKS,
        'value': range(0, 101),
    },
    'Buy Album': {
        'code': MCC_BUY_ALBUM,
        'value': range(0, 101),
    },
    'Update After Plugin Installed': {
        'code': MCC_UPDATE_AFTER_PLUGIN_INSTALLED,
        'value': 0,
    },
    'Update After Skin Installed': {
        'code': MCC_UPDATE_AFTER_SKIN_INSTALLED,
        'value': False,
    },
    'Update After Skin Installed Mini View': {
        'code': MCC_UPDATE_AFTER_SKIN_INSTALLED_MINIVIEW,
        'value': True,
    },
    'Notify UI Changed': {
        'code': MCC_NOTIFY_UI_CHANGED,
        'value': range(0, 101),
    },
    'Notify View Changed': {
        'code': MCC_NOTIFY_VIEW_CHANGED,
        'value': 0,
    },
    'Notify Before Active View Changed': {
        'code': MCC_NOTIFY_BEFORE_ACTIVE_VIEW_CHANGED,
        'value': 0,
    },
    'Notify Active View Changed': {
        'code': MCC_NOTIFY_ACTIVE_VIEW_CHANGED,
        'value': 0,
    },
    'Notify Player Info Changed': {
        'code': MCC_NOTIFY_PLAYER_INFO_CHANGED,
        'value': 'PLAYER_INFO_CHANGES nChange',
    },
    'Notify Tooltips Changed On': {
        'code': MCC_NOTIFY_TOOLTIPS_CHANGED_ON,
        'value': True,
    },
    'Notify Tooltips Changed Off': {
        'code': MCC_NOTIFY_TOOLTIPS_CHANGED_OFF,
        'value': False,
    },
    'Notify Options Changed': {
        'code': MCC_NOTIFY_OPTIONS_CHANGED,
        'value': 0,
    },
    'Update': {
        'code': MCC_UPDATE,
        'value': range(0, 101),
    },
    'Notify Focus Changed': {
        'code': MCC_NOTIFY_FOCUS_CHANGED,
        'value': 0,
    },
    'Save Properties': {
        'code': MCC_SAVE_PROPERTIES,
        'value': 0,
    },
    'Notify UI Mode Changed': {
        'code': MCC_NOTIFY_UI_MODE_CHANGED,
        'value': [
            UI_MODE_STANDARD,
            UI_MODE_MINI,
            UI_MODE_DISPLAY,
            UI_MODE_THEATER,
            UI_MODE_COVER,
            UI_MODE_COUNT
        ],
    },
    'Notify Selection Changed': {
        'code': MCC_NOTIFY_SELECTION_CHANGED,
        'value': range(0, 101),
    },
    'Notify File Changed Invalidate All': {
        'code': MCC_NOTIFY_FILE_CHANGED_INVALIDATE_ALL,
        'value': -1,
    },
    'Notify File Changed': {
        'code': MCC_NOTIFY_FILE_CHANGED,
        'value': range(0, 101),
    },
    'Notify File Status Changed Invalidate All': {
        'code': MCC_NOTIFY_FILE_STATUS_CHANGED_INVALIDATE_ALL,
        'value': -1,
    },
    'Notify File Status Changed': {
        'code': MCC_NOTIFY_FILE_STATUS_CHANGED,
        'value': range(0, 101),
    },
    'Notify File Ensure Visible': {
        'code': MCC_NOTIFY_FILE_ENSURE_VISIBLE,
        'value': range(0, 101),
    },
    'Notify Get Tab Hwnds': {
        'code': MCC_NOTIFY_GET_TAB_HWNDS,
        'value': 0,
    },
    'Notify Burner Queue Changed': {
        'code': MCC_NOTIFY_BURNER_QUEUE_CHANGED,
        'value': 1,
    },
    'Notify Burner Progress Changed': {
        'code': MCC_NOTIFY_BURNER_PROGRESS_CHANGED,
        'value': range(0, 101),
    },
    'Notify Burner Status Changed': {
        'code': MCC_NOTIFY_BURNER_STATUS_CHANGED,
        'value': 0,
    },
    'Notify Burner Started': {
        'code': MCC_NOTIFY_BURNER_STARTED,
        'value': 0,
    },
    'Notify Burner Finished Internal': {
        'code': MCC_NOTIFY_BURNER_FINISHED_INTERNAL,
        'value': 0,
    },
    'Notify Burner Finished': {
        'code': MCC_NOTIFY_BURNER_FINISHED,
        'value': 0,
    },
    'Notify Burner Failed Internal': {
        'code': MCC_NOTIFY_BURNER_FAILED_INTERNAL,
        'value': 0,
    },
    'Notify Burner Failed': {
        'code': MCC_NOTIFY_BURNER_FAILED,
        'value': 0,
    },
    'Notify Burner Close UI': {
        'code': MCC_NOTIFY_BURNER_CLOSE_UI,
        'value': 0,
    },
    'Notify Burner Prepare For Next Copy': {
        'code': MCC_NOTIFY_BURNER_PREPARE_FOR_NEXT_COPY,
        'value': 'LPCTSTR pStatus',
    },
    'Notify Rip Started': {
        'code': MCC_NOTIFY_RIP_STARTED,
        'value': 0,
    },
    'Notify Rip Finished': {
        'code': MCC_NOTIFY_RIP_FINISHED,
        'value': 0,
    },
    'Notify Rip Failed': {
        'code': MCC_NOTIFY_RIP_FAILED,
        'value': 'LPCTSTR pError',
    },
    'Notify Rip Progress Changed': {
        'code': MCC_NOTIFY_RIP_PROGRESS_CHANGED,
        'value': 0,
    },
    'Notify Rip Queue Changed': {
        'code': MCC_NOTIFY_RIP_QUEUE_CHANGED,
        'value': 0,
    },
    'Notify DVD Rip Started': {
        'code': MCC_NOTIFY_DVD_RIP_STARTED,
        'value': 0,
    },
    'Notify DVD Rip Finished': {
        'code': MCC_NOTIFY_DVD_RIP_FINISHED,
        'value': 0,
    },
    'Notify DVD Rip Failed': {
        'code': MCC_NOTIFY_DVD_RIP_FAILED,
        'value': range(0, 101),
    },
    'Notify DVD Rip Progress Changed': {
        'code': MCC_NOTIFY_DVD_RIP_PROGRESS_CHANGED,
        'value': range(0, 101),
    },
    'Notify Download Finished': {
        'code': MCC_NOTIFY_DOWNLOAD_FINISHED,
        'value': range(0, 101),
    },
    'Notify Download Finished Unknown': {
        'code': MCC_NOTIFY_DOWNLOAD_FINISHED_UNKNOWN,
        'value': -1,
    },
    'Notify Download Failed': {
        'code': MCC_NOTIFY_DOWNLOAD_FAILED,
        'value': range(0, 101),
    },
    'Notify Download Failed Unknown': {
        'code': MCC_NOTIFY_DOWNLOAD_FAILED_UNKNOWN,
        'value': -1,
    },
    'Notify Download Status Changed': {
        'code': MCC_NOTIFY_DOWNLOAD_STATUS_CHANGED,
        'value': 0,
    },
    'Notify Status Checker Complete': {
        'code': MCC_NOTIFY_STATUS_CHECKER_COMPLETE,
        'value': 0,
    },
    'Notify Current Zone Changed': {
        'code': MCC_NOTIFY_CURRENT_ZONE_CHANGED,
        'value': 0,
    },
    'Notify Display Owner Changed': {
        'code': MCC_NOTIFY_DISPLAY_OWNER_CHANGED,
        'value': 'JRWnd * pwndOwner',
    },
    'Notify After First Update Layout Window': {
        'code': MCC_NOTIFY_AFTER_FIRST_UPDATE_LAYOUT_WINDOW,
        'value': 0,
    },
    'Notify After First Update Apply View State': {
        'code': MCC_NOTIFY_AFTER_FIRST_UPDATE_APPLY_VIEW_STATE,
        'value': 0,
    },
    'Notify Process Time Remaining': {
        'code': MCC_NOTIFY_PROCESS_TIME_REMAINING,
        'value': range(0, 101),
    },
    'Notify UI Update Enable Disable States': {
        'code': MCC_NOTIFY_UI_UPDATE_ENABLE_DISABLE_STATES,
        'value': 0,
    },
    'Update Window Layout': {
        'code': MCC_UPDATE_WINDOW_LAYOUT,
        'value': 0,
    },
    'Notify Save UI Before Shutdown': {
        'code': MCC_NOTIFY_SAVE_UI_BEFORE_SHUTDOWN,
        'value': 0,
    },
    'Notify Playlist Files Changed': {
        'code': MCC_NOTIFY_PLAYLIST_FILES_CHANGED,
        'value': range(0, 101),
    },
    'Notify Playlist Info Changed': {
        'code': MCC_NOTIFY_PLAYLIST_INFO_CHANGED,
        'value': range(0, 101),
    },
    'Notify Playlist Added Internal': {
        'code': MCC_NOTIFY_PLAYLIST_ADDED_INTERNAL,
        'value': range(0, 101),
    },
    'Notify Playlist Added By User': {
        'code': MCC_NOTIFY_PLAYLIST_ADDED_BY_USER,
        'value': range(0, 101),
    },
    'Notify Playlist Removed': {
        'code': MCC_NOTIFY_PLAYLIST_REMOVED,
        'value': range(0, 101),
    },
    'Notify Playlist Collection Changed': {
        'code': MCC_NOTIFY_PLAYLIST_COLLECTION_CHANGED,
        'value': 0,
    },
    'Notify Playlist Properties Changed': {
        'code': MCC_NOTIFY_PLAYLIST_PROPERTIES_CHANGED,
        'value': range(0, 101),
    },
    'Notify Handheld Upload Started': {
        'code': MCC_NOTIFY_HANDHELD_UPLOAD_STARTED,
        'value': range(0, 101),
    },
    'Notify Handheld After Device Changed': {
        'code': MCC_NOTIFY_HANDHELD_AFTER_DEVICE_CHANGED,
        'value': 0,
    },
    'Notify Handheld Queue Changed': {
        'code': MCC_NOTIFY_HANDHELD_QUEUE_CHANGED,
        'value': 0,
    },
    'Notify Handheld Info Complete': {
        'code': MCC_NOTIFY_HANDHELD_INFO_COMPLETE,
        'value': 0,
    },
    'Notify Handheld After Upload Finished': {
        'code': MCC_NOTIFY_HANDHELD_AFTER_UPLOAD_FINISHED,
        'value': 0,
    },
    'Notify Compact Memory': {
        'code': MCC_NOTIFY_COMPACT_MEMORY,
        'value': 0,
    },
    'Notify Search Changed': {
        'code': MCC_NOTIFY_SEARCH_CHANGED,
        'value': 0,
    },
    'Notify Search Context Changed': {
        'code': MCC_NOTIFY_SEARCH_CONTEXT_CHANGED,
        'value': 0,
    },
    'Notify Update Shopping Cart': {
        'code': MCC_NOTIFY_UPDATE_SHOPPING_CART,
        'value': 'JRStoreBase * pStore',
    },
    'Notify Update Navigation Trail': {
        'code': MCC_NOTIFY_UPDATE_NAVIGATION_TRAIL,
        'value': 0,
    },
    'Notify Import Started': {
        'code': MCC_NOTIFY_IMPORT_STARTED,
        'value': False,
    },
    'Notify Import Started Silent': {
        'code': MCC_NOTIFY_IMPORT_STARTED_SILENT,
        'value': True,
    },
    'Notify Import Finished': {
        'code': MCC_NOTIFY_IMPORT_FINISHED,
        'value': False,
    },
    'Notify Import Finished Silent': {
        'code': MCC_NOTIFY_IMPORT_FINISHED_SILENT,
        'value': True,
    },
    'Notify Rotated Images': {
        'code': MCC_NOTIFY_ROTATED_IMAGES,
        'value': 'MFKEY nKey',
    },
    'Notify Login State Change': {
        'code': MCC_NOTIFY_LOGIN_STATE_CHANGE,
        'value': False,
    },
    'Notify Login State Change Logged In': {
        'code': MCC_NOTIFY_LOGIN_STATE_CHANGE_LOGGED_IN,
        'value': True,
    },
    'Notify Mygal Progress': {
        'code': MCC_NOTIFY_MYGAL_PROGRESS,
        'value': 0,
    },
    'Notify Mygal Done': {
        'code': MCC_NOTIFY_MYGAL_DONE,
        'value': 0,
    },
    'Notify Podcast Changed': {
        'code': MCC_NOTIFY_PODCAST_CHANGED,
        'value': 0,
    },
    'Notify Podcast Settings Changed': {
        'code': MCC_NOTIFY_PODCAST_SETTINGS_CHANGED,
        'value': 0,
    },
    'Notify Convert Progress': {
        'code': MCC_NOTIFY_CONVERT_PROGRESS,
        'value': 0,
    },
    'Notify Convert Update': {
        'code': MCC_NOTIFY_CONVERT_UPDATE,
        'value': 0,
    },
    'Notify Breadcrumbs Changed': {
        'code': MCC_NOTIFY_BREADCRUMBS_CHANGED,
        'value': 0,
    },
    'Notify Installed Plugins Changed': {
        'code': MCC_NOTIFY_INSTALLED_PLUGINS_CHANGED,
        'value': 0,
    },
    'Notify Suggested Music Changed': {
        'code': MCC_NOTIFY_SUGGESTED_MUSIC_CHANGED,
        'value': 0,
    },
    'Notify View Settings Changed': {
        'code': MCC_NOTIFY_VIEW_SETTINGS_CHANGED,
        'value': range(0, 101),
    },
    'Notify Before Configure View Settings': {
        'code': MCC_NOTIFY_BEFORE_CONFIGURE_VIEW_SETTINGS,
        'value': 0,
    },
    'Notify TV Recording Changed': {
        'code': MCC_NOTIFY_TV_RECORDING_CHANGED,
        'value': 0,
    },
    'Notify TV Programming GUIde Changed': {
        'code': MCC_NOTIFY_TV_PROGRAMMING_GUIDE_CHANGED,
        'value': 0,
    },
    'Notify TV Channels Changed': {
        'code': MCC_NOTIFY_TV_CHANNELS_CHANGED,
        'value': 0,
    },
    'Notify TV Recording Started': {
        'code': MCC_NOTIFY_TV_RECORDING_STARTED,
        'value': 0,
    },
    'Notify TV Recording Finished': {
        'code': MCC_NOTIFY_TV_RECORDING_FINISHED,
        'value': 0,
    },
    'Notify Import Files Added': {
        'code': MCC_NOTIFY_IMPORT_FILES_ADDED,
        'value': 0,
    },
    'Notify Playback Options Changed': {
        'code': MCC_NOTIFY_PLAYBACK_OPTIONS_CHANGED,
        'value': 0,
    },
    'Notify Before Layout User Interface': {
        'code': MCC_NOTIFY_BEFORE_LAYOUT_USER_INTERFACE,
        'value': 0,
    },
    'Notify After Layout User Interface': {
        'code': MCC_NOTIFY_AFTER_LAYOUT_USER_INTERFACE,
        'value': 0,
    },
    'Notify Zone Added Or Removed': {
        'code': MCC_NOTIFY_ZONE_ADDED_OR_REMOVED,
        'value': range(0, 101),
    },
    'Notify Zone Linked Or Unlinked': {
        'code': MCC_NOTIFY_ZONE_LINKED_OR_UNLINKED,
        'value': 0,
    },
    'Notify Library Locations Changed': {
        'code': MCC_NOTIFY_LIBRARY_LOCATIONS_CHANGED,
        'value': 0,
    },
    'Notify DSP Settings Changed In Code': {
        'code': MCC_NOTIFY_DSP_SETTINGS_CHANGED_IN_CODE,
        'value': range(0, 101),
    },
    'Notify Optical Disc Changed': {
        'code': MCC_NOTIFY_OPTICAL_DISC_CHANGED,
        'value': 0,
    },
    'Notify Store Download Status Changed': {
        'code': MCC_NOTIFY_STORE_DOWNLOAD_STATUS_CHANGED,
        'value': range(0, 101),
    },
    'Notify Current Playlist Next Item To Play Changed': {
        'code': MCC_NOTIFY_CURRENT_PLAYLIST_NEXT_ITEM_TO_PLAY_CHANGED,
        'value': range(0, 101),
    },
    'Store Download': {
        'code': MCC_STORE_DOWNLOAD,
        'value': False,
    },
    'Store Download Allow Purchase': {
        'code': MCC_STORE_DOWNLOAD_ALLOW_PURCHASE,
        'value': True,
    },
    'Store Purchase': {
        'code': MCC_STORE_PURCHASE,
        'value': 'MFKEY nKey',
    },
    'Store Search Amazon': {
        'code': MCC_STORE_SEARCH_AMAZON,
        'value': 'MFKEY nKey',
    },
    'Store Search Amazon MP3 Store': {
        'code': MCC_STORE_SEARCH_AMAZON_MP3_STORE,
        'value': 'MFKEY nKey',
    },
    'Store T-Shirt': {
        'code': MCC_STORE_TSHIRT,
        'value': 'MFKEY nKey',
    },
    'Store Change User': {
        'code': MCC_STORE_CHANGE_USER,
        'value': 0,
    },
    'Store Check For Downloads': {
        'code': MCC_STORE_CHECK_FOR_DOWNLOADS,
        'value': 0,
    }
}


def _stream_watcher(identifier, proc, stream):
    while True:
        for line in stream:
            eg.PrintDebugNotice(identifier + line)

        if proc.poll() is not None:
            break

    if not stream.closed:
        stream.close()


class SendCommand(eg.ActionBase):

    def __call__(self, zone=1, value=None):
        if self.plugin.jriver_exe is None:
            eg.PrintError('J. River Media Center is not installed')

        command, command_value = self.value

        if isinstance(command_value, list) and value is None:
            eg.PrintNotice(
                'You need to configure this action before you can use it'
            )
            return
        elif isinstance(command_value, (str, unicode)):
            eg.PrintNotice(
                'This command is not yet supported.'
            )
            return
        elif value is not None:
            command_value = value

        command_value = ' /MCC %d, %d:%d' % (command, int(command_value), zone)

        proc = Popen(
            self.plugin.jriver_exe + command_value,
            stdout=PIPE,
            stderr=PIPE,
            cwd=self.plugin.jriver_cwd
        )

        if DEBUG:

            Thread(
                target=_stream_watcher,
                name='stdout-watcher',
                args=('STDOUT:', proc, proc.stdout)
            ).start()
            Thread(
                target=_stream_watcher,
                name='stderr-watcher',
                args=('STDERR:', proc, proc.stderr)
            ).start()

    def Configure(self, zone=1, value=None):
        _, command_value = self.value

        panel = eg.ConfigPanel()

        zone_st = panel.StaticText('Zone:')
        zone_ctrl = panel.SpinIntCtrl(zone, min=1, max=99)

        zone_sizer = wx.BoxSizer(wx.HORIZONTAL)
        zone_sizer.Add(zone_st, 0, wx.EXPAND | wx.ALL, 5)
        zone_sizer.Add(zone_ctrl, 0, wx.EXPAND | wx.ALL, 5)

        panel.sizer.Add(zone_sizer, 0, wx.EXPAND)

        if isinstance(command_value, list):
            value_st = panel.StaticText('Additional Parameter:')
            value_ctrl = panel.Choice(
                0,
                choices=list(str(v) for v in command_value)
            )

            if value is not None:
                value_ctrl.SetStringSelection(str(value))

            value_sizer = wx.BoxSizer(wx.HORIZONTAL)
            value_sizer.Add(value_st, 0, wx.EXPAND | wx.ALL, 5)
            value_sizer.Add(value_ctrl, 0, wx.EXPAND | wx.ALL, 5)

            panel.sizer.Add(value_sizer, 0, wx.EXPAND)

            eg.EqualizeWidths((zone_st, value_st))
            eg.EqualizeWidths((zone_ctrl, value_ctrl))

            _get_string_selection = value_ctrl.GetStringSelection

            def get_string_selection():
                return int(_get_string_selection())

            value_ctrl.GetStringSelection = get_string_selection

        else:
            class value_ctrl:
                @staticmethod
                def GetStringSelection():
                    return None

        while panel.Affirmed():
            panel.SetResult(
                zone_ctrl.GetValue(),
                value_ctrl.GetStringSelection()
            )




class JRiverCommand(eg.PluginBase):

    def __init__(self):

        high_version = ''
        self.jriver_exe = None
        self.jriver_cwd = None

        sam = _winreg.KEY_READ
        if eg.Utils.Is64BitOS():
            sam = sam | _winreg.KEY_WOW64_64KEY

        reg_path = r'Software\J. River\Media Core\Installations'
        key = _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE, reg_path, 0, sam)
        index = 0

        while True:
            try:
                sub_key = _winreg.OpenKey(
                    key,
                    _winreg.EnumKey(key, index),
                    0,
                    sam
                )
                version = _winreg.QueryValueEx(sub_key, 'Version')
                if version > high_version:
                    high_version = version
                    self.jriver_exe = _winreg.QueryValueEx(
                        sub_key,
                        'Launcher Name'
                    )[0]
                    self.jriver_cwd = _winreg.QueryValueEx(
                        sub_key,
                        'Path'
                    )[0]
                index += 1
            except WindowsError:
                break

        if self.jriver_exe is None:
            eg.PrintError('J. River Media Center is not installed.')

        action_list = ()
        for command_description in sorted(COMMANDS.keys()):
            command_data = COMMANDS[command_description]
            code = command_data['code']
            value = command_data['value']
            class_name = 'fn' + command_description.replace(' ', '_').upper()
            action_list += ((
                SendCommand,
                class_name,
                command_description,
                command_description,
                [code, value]
            ),)

        self.AddActionsFromList(action_list)

    def __stop__(self):
        pass

    def __start__(self):
        pass
