# Copyright (c) Microsoft Corporation. All rights reserved.
# Module Name:
#   winpackagefamily.h
# Abstract:
#     API family partitioning based on packages.

from win_constants_h import *

_INC_WINPACKAGEFAMILY = None
MOFCOMP_PASS = None

if not defined(_INC_WINPACKAGEFAMILY):
    _INC_WINPACKAGEFAMILY = 1
    from winapifamily_h import *

    if defined(_MSC_VER) and not defined(MOFCOMP_PASS):
        if _MSC_VER >= 1200:
            pass
        # ENDIF defined(_MSC_VER) and not defined(MOFCOMP_PASS)
    # ENDIF defined(_MSC_VER) and not defined(MOFCOMP_PASS)
    WINAPI_PARTITION_ONECORE_APP = 0

    if not defined(WINAPI_PARTITION_SERVER):
        WINAPI_PARTITION_SERVER = (
            WINAPI_FAMILY == WINAPI_FAMILY_SERVER
        )
    # ENDIF not defined(WINAPI_PARTITION_SERVER)

    # PARTITIONS based on packages are each #undef'ed below, and then will be
    # #define-ed to be either 1 or 0 or depending on the active WINAPI_FAMILY.
    # PARTITIONS for feature packages. Each package might be active for
    # one or more editions
    WINAPI_PARTITION_PKG_WINTRUST = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_WEBSERVICES = (
        WINAPI_PARTITION_SERVER == 1
        )
    WINAPI_PARTITION_PKG_EVENTLOGSERVICE = (
        WINAPI_PARTITION_SERVER == 1
    )
    WINAPI_PARTITION_PKG_VHD = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_PERFCOUNTER = (
        WINAPI_PARTITION_SERVER == 1
    )
    WINAPI_PARTITION_PKG_SECURESTARTUP = (
        WINAPI_PARTITION_SERVER == 1
    )
    WINAPI_PARTITION_PKG_REMOTEFS = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_BOOTABLESKU = (
        WINAPI_PARTITION_SERVER == 1
    )
    WINAPI_PARTITION_PKG_CMDTOOLS = (
        WINAPI_PARTITION_SERVER == 1
    )
    WINAPI_PARTITION_PKG_DISM = (
        WINAPI_PARTITION_SERVER == 1
    )
    WINAPI_PARTITION_PKG_CORESETUP = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_APPRUNTIME = (
        WINAPI_PARTITION_SERVER == 1
    )
    WINAPI_PARTITION_PKG_ESENT = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_WINMGMT = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_WNV = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_CLUSTER = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_VSS = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_TRAFFIC = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_ISCSI = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_STORAGE = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_MPSSVC = WINAPI_PARTITION_SERVER == 1
    WINAPI_PARTITION_PKG_APPXDEPLOYMENT = (
        WINAPI_PARTITION_SERVER == 1
    )
    WINAPI_PARTITION_PKG_WER = WINAPI_PARTITION_SERVER == 1

    if defined(_MSC_VER) and not defined(MOFCOMP_PASS):
        if _MSC_VER >= 1200:
            pass
        # ENDIF if _MSC_VER >= 1200
    # endif defined(_MSC_VER) and not defined(MOFCOMP_PASS)

# ENDIF not defined(_INC_WINPACKAGEFAMILY)

__all__ = (
    'WINAPI_PARTITION_PKG_APPRUNTIME', 'WINAPI_PARTITION_PKG_BOOTABLESKU',
    'WINAPI_PARTITION_PKG_APPXDEPLOYMENT', 'WINAPI_PARTITION_PKG_CLUSTER',
    'WINAPI_PARTITION_PKG_CMDTOOLS', 'WINAPI_PARTITION_PKG_CORESETUP',
    'WINAPI_PARTITION_PKG_DISM', 'WINAPI_PARTITION_PKG_ESENT',
    'WINAPI_PARTITION_PKG_EVENTLOGSERVICE', 'WINAPI_PARTITION_PKG_ISCSI',
    'WINAPI_PARTITION_PKG_MPSSVC', 'WINAPI_PARTITION_PKG_PERFCOUNTER',
    'WINAPI_PARTITION_PKG_REMOTEFS', 'WINAPI_PARTITION_PKG_SECURESTARTUP',
    'WINAPI_PARTITION_PKG_STORAGE', 'WINAPI_PARTITION_PKG_TRAFFIC',
    'WINAPI_PARTITION_PKG_VHD', 'WINAPI_PARTITION_PKG_VSS',
    'WINAPI_PARTITION_PKG_WEBSERVICES', 'WINAPI_PARTITION_PKG_WER',
    'WINAPI_PARTITION_PKG_WINMGMT', 'WINAPI_PARTITION_PKG_WINTRUST',
    'WINAPI_PARTITION_PKG_WNV', 'WINAPI_PARTITION_ONECORE_APP'
)
