# -*- coding: utf-8 -*-
from winnt_h import STATUS_WAIT_0

FILE_FLAG_OVERLAPPED = 0x40000000
INFINITE = 0xFFFFFFFF
WAIT_FAILED = 0xFFFFFFFF

WAIT_OBJECT_0 = STATUS_WAIT_0 + 0
WAIT_OBJECT_1 = STATUS_WAIT_0 + 1
